Extend contact email optional with cc and bcc emails and the subject with the orderid
plentymarkets/plugin-ceres pull request #1002
Opened 2019-03-21 17:16 UTC by Lauflust

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io 

Requires IO update
IO PR: _comming_

2019-04-24 15:24 UTC, dbohla requested changes

2019-04-24 15:24 UTC, dbohla commented on resources/lang/de/Config.properties
> +contactShopMailCcLabel = Zusätzliche Cc E-Mail-Adressen für das Kontaktformular (Mehrere getrennt durch ein Komma)
E-Mail-Adresse für Kopie der Kontaktanfrage (CC)


Diese Info in Klammern ergänzen wir im Handbuch (mehrere Adressen kommasepariert eingeben)

2019-04-24 15:24 UTC, dbohla commented on resources/lang/de/Config.properties
> +contactShopMailBccLabel = Zusätzliche Bcc E-Mail-Adressen für das Kontaktformular (Mehrere getrennt durch ein Komma)
E-Mail-Adresse für Blindkopie der Kontaktanfrage (BCC)

Diese Info in Klammern ergänzen wir im Handbuch (mehrere Adressen kommasepariert eingeben)

2019-04-24 15:24 UTC, dbohla commented on config.json
> +                "contact.opening_times": {
Zeile 1444 bis Zeile 1461 wurden in einem [anderen PR](https://github.com/plentymarkets/plugin-ceres/pull/1067) von mir entfernt, da deprecated. Diese Zeilen können gelöscht werden, da diese Texte aus der Mehrsprachigkeit geladen werden.

2019-04-24 15:24 UTC, dbohla commented on resources/lang/de/Config.properties
> +contactOpeningTimesLabel = Öffnungszeiten (DE)
bitte entfernen

2019-04-24 15:24 UTC, dbohla commented on resources/lang/de/Config.properties
> +contactEnOpeningTimesLabel = Öffnungszeiten (EN)
bitte entfernen

2019-04-24 15:24 UTC, dbohla commented on resources/lang/en/Config.properties
> +contactOpeningTimesLabel = Opening hours (DE)
bitte entfernen

2019-04-24 15:24 UTC, dbohla commented on resources/lang/en/Config.properties
> +contactEnOpeningTimesLabel = Opening hours (EN)
bitte entfernen

2019-04-24 15:24 UTC, dbohla commented on resources/lang/en/Config.properties
> +contactShopMailCcLabel = Additional Cc email addresses of the contact form (several separated by a comma)
Email address for copy of the contact request (CC)

2019-04-24 15:24 UTC, dbohla commented on resources/lang/en/Config.properties
> +contactShopMailBccLabel = Additional Bcc email addresses of the contact form (several separated by a comma)
Email address for blind copy of the contact request (BCC)

2019-04-27 19:50 UTC, Lauflust commented
Änderungen wurden übernommen.
Du hättest auch einen PR in meinen Branch machen können.

2019-04-30 06:56 UTC, dbohla submitted a review, later dismissed

2019-04-30 06:57 UTC, dbohla commented
@plentymarkets/ceres-io Muss der PR gegen Beta gestellt werden?

2019-05-02 09:59 UTC, Lauflust commented
@dbohla @fmutschler 
Die Option `extend_orderid_to_mail_subject` wurde entfernt, da dies jetzt über die Mehrsprachigkeit geändert werden kann.

https://github.com/plentymarkets/plugin-io/pull/427#discussion_r278172104

2019-05-02 10:47 UTC, felixdausch approved these changes

2019-05-02 10:52 UTC, merged

2019-05-02 11:01 UTC, Lauflust commented
@felixdausch 
ich glaube ich habe bei den Merge conflict etwas zu viel gelöscht..

https://github.com/plentymarkets/plugin-ceres/blob/27a0efb0080cd6a1bb5ae7cdcc6293653a870aea/resources/lang/de/Config.properties#L51-L57
https://github.com/plentymarkets/plugin-ceres/blob/27a0efb0080cd6a1bb5ae7cdcc6293653a870aea/resources/lang/en/Config.properties#L51-L57