Feature/new salutation
plentymarkets/plugin-ceres pull request #1049
Opened 2019-04-04 14:33 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-04-05 08:32 UTC, felixdausch approved these changes

2019-04-09 15:37 UTC, fmutschler requested changes

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +addressDefaultSalutationTooltip = "Vorausgewählte Anrede"
```suggestion
addressDefaultSalutationTooltip = "Wählen, welche Anrede vorausgewählt ist."
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Config.properties
> +addressDefaultSalutationValueMale = Male
```suggestion
addressDefaultSalutationValueMale = Mr
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Config.properties
> +addressDefaultSalutationValueFemale = Female
```suggestion
addressDefaultSalutationValueFemale = Ms
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Config.properties
> +addressDefaultSalutationValueDiverse = Person
```suggestion
addressDefaultSalutationValueDiverse = Mx
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Template.properties
> +addressSalutationDiverse = "Person"
```suggestion
addressSalutationDiverse = "Mx"
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Template.properties
> +addressSalutationMale = "Mr."
```suggestion
addressSalutationMale = "Mr"
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Template.properties
> +addressSalutationFemale = "Ms."
```suggestion
addressSalutationFemale = "Ms"
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +addressDefaultSalutationTooltip = "Preselected salutation"
```suggestion
addressDefaultSalutationTooltip = "Select the preselected form of salutation."
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +addressDefaultSalutationValueMale = "Male"
```suggestion
addressDefaultSalutationValueMale = "Mr"
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +addressDefaultSalutationValueFemale = "Female"
```suggestion
addressDefaultSalutationValueFemale = "Ms"
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +addressDefaultSalutationValueDiverse = "Person"
```suggestion
addressDefaultSalutationValueDiverse = "Mx"
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +greetingWidgetDiverse = "Person"
```suggestion
greetingWidgetDiverse = "Mx"
```

2019-04-09 15:37 UTC, fmutschler commented on resources/lang/en/Widget.properties
>  greetingWidgetFemale = "Ms."
```suggestion
greetingWidgetFemale = "Ms"
```

2019-04-10 07:58 UTC, fmutschler approved these changes

2019-04-10 07:59 UTC, merged