FIX/ absolute and relativ header widget stacking
plentymarkets/plugin-ceres pull request #1068
Opened 2019-04-12 15:06 UTC by Tim-M-S

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-04-15 15:16 UTC, felixdausch requested changes
- In der Header.twig wird auch nochmals die Höhe des Headers berechnet, bevor das restliche Markup geladen und Vue initialisiert ist. Auf diese Weise soll verhindert werden, dass erst am Ende dieses Prozesses der Header berechnet wird und dann erst an die richtige Stelle springt
- Die Logik zum Berechnen des Headers ist inzwischen ziemlich umfangreich. Man könnte darüber nachdenken, das ganze in eine separate JS-Datei auszulagern und es nicht mehr als inline-script im PageDesign liegen zu lassen.
- Außerdem sollte man prüfen, ob die Performance auch auf weniger leistungsstarken Geräten noch gut ist, wenn bei jedem scroll alle Berechnungen durchgeführt werden. Evtl. macht es Sinn, das ganze über AnimationFrames zu optimieren.

2019-04-15 15:16 UTC, felixdausch commented on resources/views/PageDesign/PageDesign.twig
>          var header = document.getElementById('page-header');
`header` wird tatsächlich nur verwendet, um später anhand von `header.classList.contains('fixed-top')` zu prüfen, ob es sich um den ShopBuilder-Header handelt. Das könnte man genauso über `headerParent` machen. Dann wäre diese Variable überflüssig.

2019-04-15 15:16 UTC, felixdausch commented on resources/views/PageDesign/PageDesign.twig
> +        var headerParent = document.getElementById('page-header-children');
Hier ist wiederum die Benennung irreführend. Die Variable heißt `headerParent` und beinhaltet das Element mit der ID "page-header-children".

2019-04-15 15:23 UTC, Tim-M-S commented on resources/views/PageDesign/PageDesign.twig
> +        var headerParent = document.getElementById('page-header-children');
done

2019-04-15 15:26 UTC, Tim-M-S commented on resources/views/PageDesign/PageDesign.twig
>          var header = document.getElementById('page-header');
done

2019-04-16 15:57 UTC, felixdausch approved these changes

2019-04-17 08:38 UTC, merged