Address Validation - Handle server errors
plentymarkets/plugin-ceres pull request #112
Opened 2017-07-18 13:58 UTC by cjohannsen

CHANGE ValidationService.js:
- a new function has been added to the ValidationService to mark fields with the error class in address inputs, if the response from server tells, that the field is now valid. It will also check the text of this input field, to parse it into servers’ validation errors.
- function “markInvalidFields” had not the correct error class initially

CHANGE ApiService.js:
- the “_send” function will now return the whole response, instead of just the error

CHANGE AddressService.js:
- the AddressService is now matching the ES6 pattern
- the functions “createAddress” and “updateAddress” will now suppress the printing of errors by the ApiService.js

CHANGE CreateUpdateAddress.js:
- CreateUpdateAddress is now matching the ES6 pattern
- the function “validate” has been code sliced
- a new function “_handleVariationErrors” is added, to put out the validation errors in a notification
- the new function “_handleVariationErrors” is now called, if the create/update address will fail

CHANGE Notifications.twig:
- the notifications will now be put out as HTML, if they contain template markup

CHANGE CountrySelect.twig, BillingAddressInputGroupDE.twig, BillingAddressInputGroupGB.twig, DeliveryAddressInputGroupDE.twig, DeliveryAddressInputGroupGB.twig:
- all these templates will now have the data-attribute “data-model”, which is needed for the ValidationService to mark the fields with error-class, if the response from server is telling

2017-07-20 06:27 UTC, lks-mtzn commented on resources/js/src/app/services/ValidationService.js
> +    errorClass = errorClass || "error";
Wieso hast du das hier global zu error geändert?

2017-07-21 14:38 UTC, Sebsta13 requested changes

2017-07-21 14:38 UTC, Strean1337 commented on resources/js/src/app/components/customer/AddressSelect/CreateUpdateAddress/CreateUpdateAddress.js
> +            for (const i in validationErrors)
benutz hier doch einfach eine for ... of schleife oder eine for ... each dann musst du nicht mit [i] auf den wert zugreifen

2017-07-21 14:38 UTC, Strean1337 commented on resources/js/src/app/services/AddressService.js
> +    return ApiService.post("rest/io/customer/address?typeId=" + addressType, address, {supressNotifications: true})
supressNotifications wird doch über eine config Einstellung in Ceres gesetzt oder? Überschreibst du das dann nicht hier statisch?

2017-07-21 14:38 UTC, Strean1337 commented on resources/js/src/app/services/AddressService.js
> +    return ApiService.put("rest/io/customer/address/" + newData.id + "?typeId=" + addressType, newData, {supressNotifications: true});
hier das selbe

2017-07-21 14:38 UTC, Strean1337 commented on resources/js/src/app/services/ApiService.js
> +                deferred.reject(response);
wurde das serverseitig geändert?

2017-07-21 14:38 UTC, Strean1337 commented on resources/js/src/app/services/ValidationService.js
> +    errorClass = errorClass || "error";
interessiert mich auch

2017-07-21 14:38 UTC, Strean1337 commented on resources/views/Customer/Components/CountrySelect.twig
> +    <div class="input-unit" v-if="stateList != undefined && stateList.length > 0 && addressType === '1'" {% if "billing_address.stateId" in billingAddressFieldsRequired %}data-validate {% endif %} da
wenn du einfach nur auf stateList checkst dann wird automatisch auf != undefined != null und != 0 geprüft

2017-07-21 14:38 UTC, Strean1337 commented on resources/views/Customer/Components/CountrySelect.twig
> +        <div class="input-unit" v-if="stateList != undefined && stateList.length > 0 && addressType === '2'" {% if "delivery_address.stateId" in deliveryAddressFieldsRequired %}data-validate {% endif
same

2017-07-21 14:38 UTC, Strean1337 commented on resources/views/PageDesign/Components/Notifications.twig
> +            {!! notification.message !!}
kommt da html mit raus? Wegen den `<br>`?

2017-07-24 08:45 UTC, lks-mtzn commented on resources/js/src/app/components/customer/AddressSelect/CreateUpdateAddress/CreateUpdateAddress.js
> +            for (const i in validationErrors)
The for each...in statement is deprecated as the part of ECMA-357 (E4X) standard. Aber for... of. .

2017-07-24 09:57 UTC, cjohannsen commented on resources/js/src/app/services/AddressService.js
> +    return ApiService.post("rest/io/customer/address?typeId=" + addressType, address, {supressNotifications: true})
Nein das ist keine Ceres Konfig, sondern eine config für den aktuellen ApiService Restcall

2017-07-24 09:59 UTC, cjohannsen commented on resources/views/PageDesign/Components/Notifications.twig
> +            {!! notification.message !!}
genau

2017-07-24 11:37 UTC, cjohannsen commented on resources/js/src/app/components/customer/AddressSelect/CreateUpdateAddress/CreateUpdateAddress.js
> +            for (const i in validationErrors)
👍

2017-07-24 11:39 UTC, cjohannsen commented on resources/js/src/app/services/ApiService.js
> +                deferred.reject(response);
nein

2017-07-24 11:39 UTC, cjohannsen commented on resources/js/src/app/services/ValidationService.js
> +    errorClass = errorClass || "error";
weil es die Klasse "has-error" nicht gibt, sondern nur "error" hier verwendet wird

2017-07-24 12:00 UTC, merged