add crossSelling option to widget
plentymarkets/plugin-ceres pull request #1208
Opened 2019-06-14 15:20 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-06-14 15:20 UTC, stentrop commented
@fmutschler

2019-06-21 15:25 UTC, Dominik2809 approved these changes

2019-06-21 15:47 UTC, Dominik2809 requested changes

2019-06-21 15:47 UTC, Dominik2809 commented on resources/lang/en/Widget.properties
> +itemListPlaceholderDescription = ""
Warum leer?

2019-06-24 06:20 UTC, stentrop commented on resources/lang/en/Widget.properties
> +itemListPlaceholderDescription = ""
@fmutschler hat dafür eine Karte auf unserem Board

2019-06-24 09:09 UTC, fmutschler approved these changes
Habs sprachlich korrigiert

2019-06-25 08:15 UTC, Dominik2809 approved these changes

2019-06-28 07:29 UTC, Dominik2809 approved these changes

2019-06-28 10:48 UTC, merged