Legal pages/legal text widget
plentymarkets/plugin-ceres pull request #1260
Opened 2019-07-08 08:56 UTC by cjohannsen

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-07-08 09:12 UTC, fmutschler requested changes

2019-07-08 09:12 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +legalTextsLabel = "Rechtliche Texte"
```suggestion
legalTextsLabel = "Rechtstexte"
```

2019-07-08 09:12 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +legalTextsType = "Typ"
```suggestion
legalTextsType = "Rechtstext"
```

2019-07-08 09:12 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +legalTextsTypeTooltip = "Typ bestimmt die Quelle des rechtlichen Texts. Wählen."
```suggestion
legalTextsTypeTooltip = "Art des Rechtstexts wählen. "
```

2019-07-08 09:12 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +legalTextsType = "Type"
```suggestion
legalTextsType = "Legal text"
```

2019-07-08 09:12 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +legalTextsTypeTooltip = "Typ bestimmt die Quelle des rechtlichen Texts. Wählen."
```suggestion
legalTextsTypeTooltip = "Select the type of legal text."
```

2019-07-08 09:15 UTC, fmutschler approved these changes

2019-07-09 09:21 UTC, stentrop approved these changes

2019-07-09 09:26 UTC, merged