Set background color of contact-page
plentymarkets/plugin-ceres pull request #1305
Opened 2019-07-23 13:42 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-07-23 13:49 UTC, cjohannsen requested changes

2019-07-23 13:49 UTC, cjohannsen commented on resources/views/Widgets/Footer/LegalInformationWidget.twig
> +        {% if (config("Ceres.contact.shop_mail") | length > 0 and config("Ceres.contact.shop_mail") != "your@email.com") or config('IO.routing.category_contact') > 0 %}
Müsste diese Zeile nicht als Twig.if(...) geschrieben werden? Ansonsten wird das nur beim Generieren berücksichtigt.

2019-07-24 08:40 UTC, cjohannsen approved these changes

2019-07-24 08:40 UTC, cjohannsen commented on resources/scss/ceres/common/_common.scss
> +.category-contact .main .container-max
Im Original ist auf dem Container noch die Klasse .page-content, diese sorgt für ein padding-top von 1rem. Mit deinem Code haben wir zwischen Header und Content keinen Platz, wollen wir das so hinnehmen?

NEU:
![Bildschirmfoto 2019-07-23 um 15 51 52](https://user-images.githubusercontent.com/22615263/61717699-d811f800-ad61-11e9-9055-c8e3cadb4576.png)

ALT:
![Bildschirmfoto 2019-07-23 um 15 51 58](https://user-images.githubusercontent.com/22615263/61717711-de07d900-ad61-11e9-9652-c8c054398317.png)

2019-07-24 09:09 UTC, felixdausch commented on resources/scss/ceres/common/_common.scss
> +.category-contact .main .container-max
👍 hab ich noch ergänzt

2019-07-24 09:09 UTC, merged