Fix/sticky widget 4.1
plentymarkets/plugin-ceres pull request #1319
Opened 2019-07-29 17:01 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-07-30 12:47 UTC, felixdausch requested changes
Um das Sonderverhalten auf der SingleItem in den Griff zu bekommen, haben wir zuletzt die Möglichkeit geschaffen, das jeweilige Referenzelement über das data-Attribut `data-sticky-container` anzugeben. Du schaffst jetzt weitere Sonderlogik, um die bestehende Sonderlogik zu überschreiben. Wir sollten uns hier auf einen Lösungsweg einigen. Evtl. kann `data-sticky-container` verwendet werden, um die neue Einstellung am Widget zu realisieren!

2019-07-30 12:47 UTC, felixdausch commented on resources/js/src/app/helper/StickyElement.js
> +            containerRect = document.getElementById("page-body").getBoundingClientRect();
Bitte keine IDs verwenden!

2019-07-30 12:47 UTC, felixdausch commented on resources/js/src/app/helper/StickyElement.js
> +    // eslint-disable-next-line
Warum wird hier eslint disabled?

2019-07-30 12:47 UTC, felixdausch commented on resources/js/src/app/helper/StickyElement.js
> +            this.offsetTop += document.getElementById("page-header").getBoundingClientRect().height;
Bitte keine IDs verwenden!

2019-07-30 12:47 UTC, felixdausch commented on resources/js/src/app/helper/StickyElement.js
> +        if (this.el.classList.contains("stickToBody"))
CSS-Klassen sollten nach Möglichkeit nur für Styling-Zwecke verwendet werden. Um Funktionen an Elemente zu knüpfen bitte data-Attribute verwenden. Auf diese Weise wird Styling klar von JS-Funktionalität getrennt!

2019-07-30 12:47 UTC, felixdausch commented on resources/views/PageDesign/Partials/Header/Navigation.twig
> -                    <li class="btnClose"></li>
Wird das nicht mehr benötigt? Kann das zugehörige CSS dann auch entfernt werden?

2019-07-30 13:26 UTC, fmutschler approved these changes

2019-07-30 13:48 UTC, Tim-M-S commented on resources/views/PageDesign/Partials/Header/Navigation.twig
> -                    <li class="btnClose"></li>
Das CSS wird noch an anderer Stelle genutzt.

2019-07-30 13:57 UTC, Tim-M-S commented on resources/js/src/app/helper/StickyElement.js
> +    // eslint-disable-next-line
Vergessen wieder rauszunehmen

2019-07-30 15:22 UTC, Tim-M-S commented on resources/js/src/app/helper/StickyElement.js
> +        if (this.el.classList.contains("stickToBody"))
obsolet

2019-07-30 15:22 UTC, Tim-M-S commented on resources/js/src/app/helper/StickyElement.js
> +            this.offsetTop += document.getElementById("page-header").getBoundingClientRect().height;
umbau default header benötigt

2019-07-30 15:23 UTC, Tim-M-S commented on resources/js/src/app/helper/StickyElement.js
> +            containerRect = document.getElementById("page-body").getBoundingClientRect();
obsolet

2019-07-30 15:23 UTC, Tim-M-S commented
> Um das Sonderverhalten auf der SingleItem in den Griff zu bekommen, haben wir zuletzt die Möglichkeit geschaffen, das jeweilige Referenzelement über das data-Attribut `data-sticky-container` anzugeben. Du schaffst jetzt weitere Sonderlogik, um die bestehende Sonderlogik zu überschreiben. Wir sollten uns hier auf einen Lösungsweg einigen. Evtl. kann `data-sticky-container` verwendet werden, um die neue Einstellung am Widget zu realisieren!

data-sticky-container wird jetzt verwendet

2019-07-31 07:47 UTC, felixdausch requested changes

2019-07-31 07:47 UTC, felixdausch commented on resources/lang/de/Widget.properties
> +stickyContainerStickTooltip = "Scroll-Verhalten des Sticky Containera wählen."
```suggestion
stickyContainerStickTooltip = "Scroll-Verhalten des Sticky Containers wählen."
```

2019-07-31 07:47 UTC, felixdausch commented on resources/views/Item/Components/SingleItem.twig
> +                        <div v-stick-in-parent data-sticky-container="#page-body">
Dadurch könnten wir doch die ID 'item-container' von dem Element entfernen?

2019-07-31 07:47 UTC, felixdausch commented on resources/views/PageDesign/Partials/Header/Header.twig
> +            <div id="page-header-parent" class="col-12 page-header-parent">
Auch hier wird wieder Funktionalität mit Styling vermischt. Brauchen wir die ID noch an anderer Stelle? Ansonsten könnten wir die ID entfernen und auf ein data-Attribut wechseln. Der Wechsel von ID auf CSS-Klasse verschiebt das Problem nur.

2019-07-31 07:47 UTC, felixdausch commented on resources/views/PageDesign/Partials/Header/Navigation.twig
> -                    <li class="btnClose"></li>
Ok. Und der Button wird an dieser Stelle nicht mehr benötigt? Ich verstehe den Zusammenhang zum Sticky-Container nicht.

2019-07-31 08:31 UTC, Tim-M-S commented on resources/views/PageDesign/Partials/Header/Navigation.twig
> -                    <li class="btnClose"></li>
Hab ich reverted und mache einen anderen Branche für auf

2019-07-31 08:37 UTC, Tim-M-S commented on resources/views/Item/Components/SingleItem.twig
> +                        <div v-stick-in-parent data-sticky-container="#page-body">
done

2019-07-31 13:27 UTC, felixdausch approved these changes

2019-07-31 13:33 UTC, merged