Feature/variation select make content hideable
plentymarkets/plugin-ceres pull request #1355
Opened 2019-08-09 13:56 UTC by cjohannsen

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-08-12 08:38 UTC, felixdausch requested changes

2019-08-12 08:38 UTC, felixdausch commented on resources/lang/de/Widget.properties
> +attributeDisplayContentAlwaysLabel = "Immer Inhalte-Auswahl anzeigen"
@fmutschler

2019-08-12 08:38 UTC, felixdausch commented on resources/js/src/app/components/item/VariationSelect.js
> +            const possibleUnits = {};
Da hier potentiell über alle Varianten iteriert wird und der getter sehr oft aufgerufen wird, könnte hier ein Performance-Problem entstehen. Das Ergebnis des getters hängt allerdings ausschließlich von den Properties ab. Evtl. kann man die Berechnung einmalig bzw. gezielt bei Änderungen ermitteln.

2019-08-12 08:38 UTC, felixdausch commented on resources/js/src/app/components/item/VariationSelect.js
> +        displayContentAlways:
Besser wäre "alwaysDisplayContent" oder etwas kürzeres wie "forceContent"

2019-08-12 09:02 UTC, fmutschler approved these changes

2019-08-15 09:43 UTC, cjohannsen commented on resources/js/src/app/components/item/VariationSelect.js
> +            const possibleUnits = {};
Haben wir drüber geredet 👍

2019-08-15 09:44 UTC, cjohannsen commented on resources/js/src/app/components/item/VariationSelect.js
> +        displayContentAlways:
Ich habe den Wert umbenannt zu "forceContent", hier der Commit: https://github.com/plentymarkets/plugin-ceres/pull/1355/commits/c8bfc148005af4960920d865f1d563f0d7a90f1f

2019-08-15 09:44 UTC, cjohannsen commented on resources/js/src/app/components/item/VariationSelect.js
> +        displayContentAlways:
Ich habe den Wert umbenannt zu "forceContent", hier der Commit: https://github.com/plentymarkets/plugin-ceres/pull/1355/commits/c8bfc148005af4960920d865f1d563f0d7a90f1f

2019-08-15 09:44 UTC, cjohannsen commented on resources/js/src/app/components/item/VariationSelect.js
> +            const possibleUnits = {};
Haben wir drüber gesprochen 👍

2019-08-15 15:23 UTC, felixdausch approved these changes

2019-08-16 09:33 UTC, merged