Sb order confirmation/items bought widget
plentymarkets/plugin-ceres pull request #1367
Opened 2019-08-15 10:08 UTC by Tim-M-S

### All changes meet the following requirements
~~[ ] Changelog entry was added~~
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-08-15 11:03 UTC, fmutschler requested changes

2019-08-15 11:03 UTC, fmutschler commented on resources/lang/en/Template.properties
> +orderConfirmationProperties = "Order properties"
```suggestion
orderConfirmationProperties = "Order characteristics"
```

2019-08-15 11:03 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +itemsBoughtLabel = "Items bought"
```suggestion
itemsBoughtLabel = "Purchased items"
```

2019-08-16 08:52 UTC, Tim-M-S commented on resources/lang/en/Template.properties
> +orderConfirmationProperties = "Order properties"
done

2019-08-16 08:52 UTC, Tim-M-S commented on resources/lang/en/Widget.properties
> +itemsBoughtLabel = "Items bought"
done

2019-08-19 09:39 UTC, closed without merging

2019-08-19 09:39 UTC, Tim-M-S commented
closed