Sb order confirmation/purchased items widget 2
plentymarkets/plugin-ceres pull request #1372
Opened 2019-08-19 09:38 UTC by Tim-M-S

### All changes meet the following requirements
~~[ ] Changelog entry was added~~
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-08-20 08:53 UTC, cjohannsen submitted a review, later dismissed

2019-08-20 08:53 UTC, cjohannsen commented on resources/views/Widgets/Checkout/PurchasedItemsWidget.twig
> +        {% for item in orderData.order.orderItems %}
Bitte noch auf den TwigBuilder umbauen

2019-08-21 07:25 UTC, Tim-M-S commented on resources/views/Widgets/Checkout/PurchasedItemsWidget.twig
> +        {% for item in orderData.order.orderItems %}
done

2019-08-21 08:38 UTC, lks-mtzn requested changes

2019-08-21 08:38 UTC, lks-mtzn commented on resources/views/Widgets/Checkout/PurchasedItemsWidget.twig
> +                                {{ Twig.print('orderItemName') }}
```suggestion
                                {{ Twig.print(Twig.call("ItemName.get", ["$item.orderItemName", "$item.bundleType"])) }}
```

2019-08-21 09:43 UTC, Tim-M-S commented on resources/views/Widgets/Checkout/PurchasedItemsWidget.twig
> +                                {{ Twig.print('orderItemName') }}
done

2019-08-21 09:44 UTC, lks-mtzn approved these changes

2019-08-21 09:50 UTC, merged