Feature/sb order confirmation/linkwidget
plentymarkets/plugin-ceres pull request #1374
Opened 2019-08-20 10:18 UTC by felixgehrmann

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io 

- Icon is now a include for widgets
- LinkWidget added

2019-08-21 08:09 UTC, Tim-M-S commented on resources/views/Widgets/Common/LinkWidget.json
> +                    "defaultValue": "btn-sm",
default md

2019-08-21 08:09 UTC, Tim-M-S commented on resources/views/Widgets/Common/LinkWidget.twig
> +    <a class="btn btn-primary btn-appearance {{ size }} {% if block %}btn-block{% endif %} {% if spacingMargin | length > 0 %}{{ spacingMargin }}{% endif %} {% if spacingPadding | length > 0 %}{{ spa
btn-{{ size }}

2019-08-21 08:09 UTC, Tim-M-S commented on resources/views/Widgets/Common/LinkWidget.json
> +                                "value": "btn-sm",
statt btn-sm nur sm

2019-08-21 08:09 UTC, Tim-M-S commented on resources/views/Widgets/Common/LinkWidget.json
> +                                "value": "btn-md",
s.o.

2019-08-21 08:09 UTC, Tim-M-S commented on resources/views/Widgets/Common/LinkWidget.json
> +                                "value": "btn-lg",
s.o.

2019-08-21 08:09 UTC, Tim-M-S commented on resources/views/Widgets/Common/LinkWidget.twig
> +    <a class="btn btn-primary btn-appearance {{ size }} {% if block %}btn-block{% endif %} {% if spacingMargin | length > 0 %}{{ spacingMargin }}{% endif %} {% if spacingPadding | length > 0 %}{{ spa
btn-primary muss da raus sonst ist der button im default nicht none

2019-08-21 08:41 UTC, fmutschler approved these changes

2019-08-21 08:48 UTC, felixgehrmann commented on resources/views/Widgets/Common/LinkWidget.json
> +                    "defaultValue": "btn-sm",
done

2019-08-21 14:56 UTC, felixdausch requested changes

2019-08-21 14:56 UTC, felixdausch commented on resources/lang/en/Widget.properties
> +urlRetoureLabel = "Return"
Korrekte Bezeichnung wäre `urlReturnLabel`

2019-08-21 14:56 UTC, felixdausch commented on resources/lang/de/Widget.properties
> +urlRetoureLabel = "Retoure"
Korrekte Bezeichnung wäre `urlReturnLabel`

2019-08-21 14:56 UTC, felixdausch commented on resources/views/Widgets/Common/LinkWidget.json
> +                        "value": "retoure",
Bitte "return" statt "retoure"

2019-08-26 15:33 UTC, felixdausch approved these changes

2019-08-29 14:59 UTC, merged