Sprint/finish him
plentymarkets/plugin-ceres pull request #139
Opened 2017-08-21 11:20 UTC by chkolb

2017-08-21 11:29 UTC, Sebsta13 requested changes
passt das mal bitte an

2017-08-21 11:29 UTC, Strean1337 commented on resources/views/MyAccount/Components/ChangePaymentMethod.twig
> +    <!-- ************************ MYACCOUNT ************************* -->
ändert das bitte zu: `<!-- MyAccount -->`

2017-08-21 11:29 UTC, Strean1337 commented on resources/views/MyAccount/Components/ChangePaymentMethod.twig
> +    <!-- ***************************** END ***************************** -->
ändert das bitte zu: `<!-- ./MyAccount -->`

2017-08-21 11:29 UTC, Strean1337 commented on resources/views/MyAccount/Components/ChangePaymentMethod.twig
> +    <!-- ************************ CONFIRMATION ************************* -->
das selbe wie oben

2017-08-21 11:29 UTC, Strean1337 commented on resources/views/MyAccount/Components/ChangePaymentMethod.twig
> +    <!-- ***************************** END ***************************** -->
same

2017-08-21 11:29 UTC, Strean1337 commented on resources/views/MyAccount/Components/ChangePaymentMethod.twig
>      <!-- CHANGE_PAYMENT_MODAL -->
hier ist es richtig

2017-08-21 11:40 UTC, Sebsta13 requested changes

2017-08-21 11:40 UTC, Strean1337 commented on resources/js/src/app/components/myAccount/ChangePaymentMethod.js
> +                    if (response === true)
this.changePossible = typeof response === "object" ? response.data : response;

damit kann man die 3 if else etc. anweisungen sparen

2017-08-21 11:40 UTC, Strean1337 commented on resources/scss/ceres/views/Confirmation/_confirmation-order-item.scss
> +	color: #008ebd!important;
keine festen hex codes.

2017-08-21 11:40 UTC, Strean1337 commented on resources/views/Checkout/OrderDetails.twig
> +                            {% set paymentStatus = '' %}
wieso wird hier set paymentStatus = '' gemacht?

2017-08-21 11:40 UTC, Strean1337 commented on resources/views/Checkout/OrderDetails.twig
> +                                                        :current-template="{{ currentTemplate | json_encode() }}">
@longhat-plenty du hast es getan 🔍

2017-08-21 12:30 UTC, longhat-plenty commented on resources/scss/ceres/views/Confirmation/_confirmation-order-item.scss
> +	color: #008ebd!important;
Hups. das hier gehört da hin --> $brand-primary: #008ebd;

2017-08-21 12:33 UTC, longhat-plenty commented on resources/views/Checkout/OrderDetails.twig
> +                            {% set paymentStatus = '' %}
Ich bin Hochsprachen gewöhnt in denen Variablen, die man in Schleifen deklariert, nicht ausserhalb dieser nutzen kann. Twig scheint das nicht zu haben. Kann also raus. Aber vorher bitte testen :) @chkolb

2017-08-21 12:38 UTC, longhat-plenty commented on resources/views/Checkout/OrderDetails.twig
> +                                                        :current-template="{{ currentTemplate | json_encode() }}">
Ich wollte eigentlich dann noch ein drittes if reinbringen für alle anderen Möglichkeiten wenn man den container verknüpft, vergessen :D 

Aber irgendwie ist hier im Git-Hub auch nicht die richtige Stelle angezeigt, aber das meintest du doch oder?

2017-08-29 15:10 UTC, Sebsta13 approved these changes

2017-08-30 08:06 UTC, closed without merging