Sb order confirmation/widgets styling2
plentymarkets/plugin-ceres pull request #1398
Opened 2019-08-23 15:50 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-08-27 12:16 UTC, cjohannsen requested changes

2019-08-27 12:16 UTC, cjohannsen commented on resources/views/Widgets/OrderConfirmation/OrderTotalsWidget.twig
> +        {% if spacingPadding | length > 0 %} {{ spacingPadding }}{% else %} px-4 pt-3{% endif %}
Die Margin Einstellungen haben keine Wirkung, da die Variablen wie "spacingPadding" nirgendwo gesetzt werden.

2019-08-27 12:16 UTC, cjohannsen commented on resources/views/Widgets/OrderConfirmation/OrderDataWidget.twig
> +        {# {{ Twig.if("shippingDate") }} #}
Soll das hier wieder einkommentiert werden?

2019-08-28 08:06 UTC, Tim-M-S commented on resources/views/Widgets/OrderConfirmation/OrderTotalsWidget.twig
> +        {% if spacingPadding | length > 0 %} {{ spacingPadding }}{% else %} px-4 pt-3{% endif %}
done

2019-08-28 08:09 UTC, Tim-M-S commented on resources/views/Widgets/OrderConfirmation/OrderDataWidget.twig
> +        {# {{ Twig.if("shippingDate") }} #}
done

2019-08-28 09:35 UTC, cjohannsen approved these changes

2019-08-28 09:35 UTC, merged