Sb static pages/login widget
plentymarkets/plugin-ceres pull request #1417
Opened 2019-08-29 14:19 UTC by lks-mtzn

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-08-29 15:15 UTC, felixdausch requested changes

2019-08-29 15:15 UTC, felixdausch commented on resources/views/Widgets/Login/LoginWidget.twig
> +    {{ Twig.if("not (services.customer.getContactId() > 0 or services.sessionStorage.getSessionValue('guestEmail') | trim is not empty) or #{ isPreview | json_encode }") }}
Ich würde im `AuthenticationService` eine Methode `isLoggedIn()` ergänzen, die diese Bedingung prüft. Dort kann man wie gewohnt über die Konstante `SessionStorageKeys::GUEST_EMAIL` auf die Gastadresse zugreifen.

2019-09-02 08:55 UTC, cjohannsen requested changes

2019-09-02 08:55 UTC, cjohannsen commented on resources/views/Widgets/Login/LoginWidget.json
> +            "defaultValue": "primary",
in dem widget ist der default "none", hier ist er primary

2019-09-02 08:55 UTC, cjohannsen commented on resources/views/Widgets/Login/LoginWidget.twig
> +{% set appearance = widget.settings.appearance.mobile | default("none") %}
in der json ist der default "primary", hier ist er "none"

2019-09-02 08:55 UTC, cjohannsen commented on resources/views/Widgets/Login/LoginWidget.twig
> +    {{ Twig.if("not services.authentication.isLoggedIn() or #{ isPreview | json_encode }") }}
Sollte diese Bedingung nicht um das äußerste div von dem Widget? Mal angenommen jemand stellt hier riesen Margin ein und dann wird das widget ausgeblendet, weil der Nutzer schon eingeloggt ist. Dann würde trotzdem der Abstand im markup bleiben

2019-09-02 09:16 UTC, cjohannsen approved these changes

2019-09-02 13:25 UTC, merged