Shipping country widget
plentymarkets/plugin-ceres pull request #1421
Opened 2019-08-30 12:43 UTC by cjohannsen

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-08-30 12:53 UTC, fmutschler requested changes

2019-08-30 12:53 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +shippingCountryLabel = "Shipping country select"
```suggestion
shippingCountryLabel = "Country of delivery selection"
```

2019-08-30 14:23 UTC, fmutschler submitted a review, later dismissed

2019-09-02 09:31 UTC, felixdausch approved these changes

2019-09-02 09:43 UTC, cjohannsen commented on resources/views/Widgets/Basket/ShippingCountryWidget.json
> +        "appearance": {
mach die Appearance raus!

2019-09-02 16:59 UTC, cjohannsen commented on resources/views/Widgets/Basket/ShippingCountryWidget.json
> +        "appearance": {
done

2019-09-02 17:01 UTC, merged