Fix/search param ignore
plentymarkets/plugin-ceres pull request #1447
Opened 2019-09-09 14:00 UTC by felixgehrmann

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-09-11 07:37 UTC, felixdausch requested changes

2019-09-11 07:37 UTC, felixdausch commented on src/Helper/SearchOptions.php
> +    public static function validateItemListOptions($itemListOptions, $defaultItemsPerPage, $scope)
Ich würde die Validierung auf gültige Werte innerhalb von `ItemListContext::initItemList()` verbauen. Auf diese Weise profitieren autom. alle externen Plugins, die sich einen eigenen Context gebaut haben, ebenfalls von den Änderungen, ohne ihren Code anpassen zu müssen.

2019-09-11 07:37 UTC, felixdausch commented on src/Helper/SearchOptions.php
> +        if( !in_array($itemListOptions['sorting'], $sortingStrings->sorting) ) {
Anstatt das Array per array_flip umzudrehen und zu durchsuchen kannst du auch mit `array_key_exists` auf den Originaldaten arbeiten.

2019-09-11 09:03 UTC, felixgehrmann commented on src/Helper/SearchOptions.php
> +    public static function validateItemListOptions($itemListOptions, $defaultItemsPerPage, $scope)
Muss so, wegen den defaultSearchFactories, die eine Ebene höher instanziiert werden.

2019-09-11 09:15 UTC, felixgehrmann commented on src/Helper/SearchOptions.php
> +        if( !in_array($itemListOptions['sorting'], $sortingStrings->sorting) ) {
done

2019-09-11 16:02 UTC, felixdausch requested changes

2019-09-11 16:02 UTC, felixdausch commented on src/Contexts/ItemSearchContext.php
> +        $defaultItemsPerPage = $this->ceresConfig->pagination->rowsPerPage[0] * $this->ceresConfig->pagination->columnsPerPage;
Warum verschiebst du die Berechnung dieses Werts nicht in die Funktion, anstatt sie von außen zu übergeben?

2019-09-12 11:44 UTC, felixgehrmann commented on src/Contexts/ItemSearchContext.php
> +        $defaultItemsPerPage = $this->ceresConfig->pagination->rowsPerPage[0] * $this->ceresConfig->pagination->columnsPerPage;
done

2019-09-13 15:55 UTC, felixdausch requested changes

2019-09-13 15:55 UTC, felixdausch commented on src/Helper/SearchOptions.php
> +        $sortingStrings = self::get($scope);
Du kannst dir hier einfach eine neue Instanz der CeresConfig erstellen. Dann sparst du dir einen Parameter komplett.

2019-09-16 09:53 UTC, felixgehrmann commented on src/Helper/SearchOptions.php
> +        $sortingStrings = self::get($scope);
done

2019-09-16 09:59 UTC, felixdausch requested changes

2019-09-16 09:59 UTC, felixdausch commented on src/Helper/SearchOptions.php
> +            $ceresConfig = pluginApp(CeresConfig::class);
Erzeuge die Klasse bitte außerhalb der if-Anweisung und ergänze noch eine Typ-Annotation `/** @var CeresConfig $ceresConfig **/`

2019-09-16 12:38 UTC, felixgehrmann commented on src/Helper/SearchOptions.php
> +            $ceresConfig = pluginApp(CeresConfig::class);
done

2019-09-16 12:41 UTC, felixdausch approved these changes

2019-09-16 12:43 UTC, merged