Fix/meta title homepage ignore category name
plentymarkets/plugin-ceres pull request #1448
Opened 2019-09-09 15:19 UTC by cjohannsen

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-09-10 15:59 UTC, felixgehrmann approved these changes

2019-09-11 07:22 UTC, felixdausch requested changes
Das würde ich nicht so machen, weil die Lösung nur für den Titel funktioniert. Wenn wir irgendwann an dem Punkt sind, dass wir die Beschreibung festlegen wollen, haben wir wieder dasselbe Problem. Mein Vorschlag wäre, für alle Werte einen defaultValue festzulegen, in den die Werte der Kategorie geschrieben werden. Diese können dann per default()-Filter gesetzt werden:

```
{% set defaultTitle = '' %}
{% if category is defined and category is not null %}
  {% set defaultTitle = category.details[0].name %}
{% endif %}

{% set title = block('title') | default(defaultTitle) is  %}

2019-09-12 07:02 UTC, felixdausch commented
Eventuell hilft dieser Ansatz: https://twigfiddle.com/rgs1u9

2019-09-12 08:29 UTC, cjohannsen commented
> Eventuell hilft dieser Ansatz: https://twigfiddle.com/rgs1u9

danke 👍 #

2019-09-16 09:07 UTC, felixdausch requested changes

2019-09-16 09:07 UTC, felixdausch commented on resources/views/PageDesign/Partials/PageMetadata.twig
> +{% set details = category.details[0] %}
Führt das zu Problemen, wenn `category` nicht existiert? Ich würde hier auch nochmal die entsprechende Abfrage einbauen

2019-09-16 14:09 UTC, felixdausch approved these changes

2019-09-16 14:09 UTC, merged