add routing to shopbuilder for change-mail
plentymarkets/plugin-ceres pull request #1470
Opened 2019-09-16 12:19 UTC by felixgehrmann

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-09-16 14:48 UTC, felixdausch requested changes

2019-09-16 14:48 UTC, felixdausch commented on resources/lang/de/Config.properties
> +routingCategoryChangeMail = Kategorie für E-Mail Änderung
@fmutschler 
Evtl. ist hier eine einheitliche Formulierung zum Widget sinnvoll:
https://github.com/plentymarkets/plugin-ceres/pull/1471/files

2019-09-16 16:12 UTC, fmutschler commented on resources/lang/de/Config.properties
> +routingCategoryChangeMail = Kategorie für E-Mail Änderung
Ich verstehe nicht genau, worauf du hier verlinkst. Meinst du dieBenennungen der Routing-Keys?

2019-09-17 10:47 UTC, felixdausch commented on resources/lang/de/Config.properties
> +routingCategoryChangeMail = Kategorie für E-Mail Änderung
Nein. Es geht um die Seite, auf die der Benutzer gelangt, wenn er die Änderung seiner E-Mail-Adresse bestätigen will. Dafür gibt es ein Widget, dass das entsprechende Formular bereitstellt. Ich würde die Benennung des Widgets und die Benennung des Kategorie-Labels vereinheitlichen

2019-09-17 15:15 UTC, fmutschler approved these changes

2019-09-18 09:18 UTC, felixdausch approved these changes

2019-09-18 09:19 UTC, merged