Fix/change coupon position totals
plentymarkets/plugin-ceres pull request #1593
Opened 2019-10-30 09:14 UTC by Tim-M-S

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-10-30 13:43 UTC, felixdausch requested changes

2019-10-30 13:43 UTC, felixdausch commented on resources/views/Basket/Components/BasketTotals.twig
> +
Ich würde es noch nach den LayoutContainer "AfterShippingCosts" packen, damit der Container-Name weiterhin die Position richtig beschreibt.

2019-10-31 17:48 UTC, Tim-M-S commented on resources/views/Basket/Components/BasketTotals.twig
> +
done

2019-11-01 10:51 UTC, felixdausch approved these changes

2019-11-01 10:52 UTC, merged