deprecated setting
plentymarkets/plugin-ceres pull request #1600
Opened 2019-10-31 18:05 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-11-01 10:28 UTC, stentrop approved these changes

2019-11-01 13:50 UTC, cjohannsen requested changes

2019-11-01 13:50 UTC, cjohannsen commented on config.json
> +                    "deprecated": true,
muss die Einstellung "sort.defaultSorting" nicht auch mit 'deprecated' geflaggt werden?

2019-11-01 13:52 UTC, stentrop commented on config.json
> +                    "deprecated": true,
nö

2019-11-01 13:57 UTC, cjohannsen approved these changes

2019-11-04 12:39 UTC, merged

2020-05-13 15:40 UTC, maxhelligeplenty commented
Hallo  ,
Merged #1600 into feature/beta/sb_categoryitem.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-ceres/pull/1600#event-2767523511

Test.test.test