sb_categoryitem/item_sorting_widget_new
plentymarkets/plugin-ceres pull request #1606
Opened 2019-11-04 12:25 UTC by Tim-M-S

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-11-04 13:45 UTC, stentrop commented on src/Widgets/Category/ItemSortingWidget.php
> +        $temp = [];
```suggestion
```

2019-11-04 13:46 UTC, stentrop commented on src/Widgets/Category/ItemSortingWidget.php
> +        $temp = [];
Wird nur im if gebraucht, dann müssen wir nicht vorher den Platz reservieren

2019-11-04 13:48 UTC, stentrop requested changes
Die Fehler beheben wir besprochen

2019-11-04 13:54 UTC, Tim-M-S commented on src/Widgets/Category/ItemSortingWidget.php
> +        $temp = [];
done

2019-11-05 12:45 UTC, stentrop approved these changes

2019-11-05 12:57 UTC, merged

2020-05-13 15:40 UTC, maxhelligeplenty commented
Hallo  ,
### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io 
You can view, comment on, or merge this pull request online at:

  https://github.com/plentymarkets/plugin-ceres/pull/1606

-- Commit Summary --

  * cleaned pull request

-- File Changes --

    M contentWidgets.json (149)
    M resources/lang/de/Widget.properties (4)
    M resources/lang/en/Widget.properties (4)
    M resources/scss/ceres/widgets/Category/_toolbar-widget.scss (4)
    A resources/views/Widgets/Category/ItemSortingWidget.json (113)
    A resources/views/Widgets/Category/ItemSortingWidget.twig (31)
    A src/Widgets/Category/ItemSortingWidget.php (45)

-- Patch Links --

https://github.com/plentymarkets/plugin-ceres/pull/1606.patch
https://github.com/plentymarkets/plugin-ceres/pull/1606.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-ceres/pull/1606


Test.test.test

2020-05-13 16:01 UTC, maxhelligeplenty commented
Hallo  ,
stentrop commented on this pull request.



> @@ -0,0 +1,45 @@
+
+
+namespace Ceres\Widgets\Category;
+
+use Ceres\Config\CeresConfig;
+use Ceres\Widgets\Helper\BaseWidget;
+use Ceres\Helper\SearchOptions;
+
+class ItemSortingWidget extends BaseWidget
+{
+    protected $template = "Ceres::Widgets.Category.ItemSortingWidget";
+
+    protected function getTemplateData($widgetSettings, $isPreview)
+    {
+        $temp = [];

```suggestion
```

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-ceres/pull/1606#pullrequestreview-311065995

Test.test.test

2020-05-13 16:01 UTC, maxhelligeplenty commented
Hallo  ,
stentrop commented on this pull request.



> @@ -0,0 +1,45 @@
+
+
+namespace Ceres\Widgets\Category;
+
+use Ceres\Config\CeresConfig;
+use Ceres\Widgets\Helper\BaseWidget;
+use Ceres\Helper\SearchOptions;
+
+class ItemSortingWidget extends BaseWidget
+{
+    protected $template = "Ceres::Widgets.Category.ItemSortingWidget";
+
+    protected function getTemplateData($widgetSettings, $isPreview)
+    {
+        $temp = [];

Wird nur im if gebraucht, dann müssen wir nicht vorher den Platz reservieren

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-ceres/pull/1606#discussion_r342056136

Test.test.test

2020-05-13 16:02 UTC, maxhelligeplenty commented
Hallo  ,
stentrop requested changes on this pull request.

Die Fehler beheben wir besprochen



-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-ceres/pull/1606#pullrequestreview-311078236

Test.test.test

2020-05-13 16:02 UTC, maxhelligeplenty commented
Hallo  ,
Tim-M-S commented on this pull request.



> @@ -0,0 +1,45 @@
+
+
+namespace Ceres\Widgets\Category;
+
+use Ceres\Config\CeresConfig;
+use Ceres\Widgets\Helper\BaseWidget;
+use Ceres\Helper\SearchOptions;
+
+class ItemSortingWidget extends BaseWidget
+{
+    protected $template = "Ceres::Widgets.Category.ItemSortingWidget";
+
+    protected function getTemplateData($widgetSettings, $isPreview)
+    {
+        $temp = [];

done

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-ceres/pull/1606#discussion_r342059701

Test.test.test