Feature/tags
plentymarkets/plugin-ceres pull request #1638
Opened 2019-11-12 15:10 UTC by maxiroellplenty

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-11-12 15:13 UTC, maxiroellplenty commented on resources/views/Item/Components/SingleItem/SingleItem_Details.twig
> +<tags></tags>
TODO

2019-11-18 16:06 UTC, felixdausch requested changes
Bitte im Changelog ein TODO ergänzen, dass die Benennung der Tags geprüft werden muss, da diese ab sofort über den Webshop erreichbar sind. Andernfalls Tag-Route deaktivieren.

2019-11-18 16:06 UTC, felixdausch commented on resources/js/src/app/components/item/Tags.js
> +                return (((red * 0.299) + (green * 0.587) + (blue * 0.114)) > 186) ? "#000000" : "#FFFFFF";
Es gibt hier die SCSS-Variablen `$yiq-text-dark` bzw. `$yiq-text-light`, um genau diese beiden Schriftfarben festzulegen. Es wäre also cooler, hier anstatt den Farbwerten `#000000` bzw. `#FFFFFF` css-Klassen mit den entsprechenden Variablen-Werten zu setzen.

2019-11-18 16:06 UTC, felixdausch commented on resources/views/Item/Components/Tags.twig
> +           @click="navigateToSearch(tag)"
Statt click-Event und js-seitiger Navigation wäre ein href-Attribut deutlich schöner

2019-11-18 16:06 UTC, felixdausch commented on resources/views/Item/Components/Tags.twig
> +           class="badge cursor-pointer mr-1"
Wenn du ein href-Attribut setzt, brauchst du auch die Klasse `cursor-pointer` nicht mehr.

2019-11-18 16:06 UTC, felixdausch commented on resources/scss/ceres/common/_common.scss
> +.cursor-pointer
Wird nicht benötigt (s. Template)

2019-11-18 16:06 UTC, felixdausch commented on resources/views/ResultFields/SingleItem.fields.json
> +    "tags.*"
Bitte die Wildcard auflösen und alle benötigten Felder auflisten. So umgehen wir die Gefahr, dass ungewollte Datenmengen ins Markup gelangen

2019-12-09 15:32 UTC, felixdausch requested changes

2019-12-09 15:32 UTC, felixdausch commented on resources/js/src/app/components/item/Tags.js
> +Vue.component("tags", {
Ich würde die Komponente nochmal umbenennen. Die Konvention ist eher die, wiederholende Elemente als `list` zu bezeichnenen (`basket-item-list`, `order-history-list`). Dementsprechend müsste diese Komponente `tag-list` heißen.

2019-12-13 16:36 UTC, felixdausch requested changes

2019-12-13 16:36 UTC, felixdausch commented on resources/lang/de/Widget.properties
> +=======
Konflikte auflösen!

2019-12-13 16:36 UTC, felixdausch commented on resources/lang/de/Template.properties
> +tagSearchResults = "Mit Tag: ":searchString" verknüpfte Artikel"
@fmutschler ist der ":" innerhalb des Satzes gewollt? z.B. »Mit Tag: "Angebot" verknüpfte Artikel«

2019-12-13 16:36 UTC, felixdausch commented on resources/lang/en/Widget.properties
> +=======
Konflikte auflösen!

2019-12-13 16:36 UTC, felixdausch commented on resources/views/Category/Item/CategoryItem.twig
> +            {% if category is not defined or catgory is null and isSearch %}
Reicht hier nicht die Abfrage auf `isSearch`?

2019-12-16 09:44 UTC, felixdausch approved these changes

2019-12-16 09:45 UTC, merged