Widget classes: Checkout widgets
plentymarkets/plugin-ceres pull request #1660
Opened 2019-11-15 17:40 UTC by felixgehrmann

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-11-15 19:18 UTC, felixgehrmann commented
Work on widget group is mostly done, requires features in SettingFactories to be completed.
#1661 for maxPerPage WidgetData
Ability to add tooltips is missing from SettingFactories.

2019-11-18 08:08 UTC, felixdausch commented
With the changes of https://github.com/plentymarkets/plugin-ceres/pull/1659 you can use `ValueListFactory::make()` for more streamlined code

2019-11-18 10:56 UTC, felixgehrmann commented
Ready for review.

2019-11-18 15:10 UTC, felixdausch requested changes

2019-11-18 15:10 UTC, felixdausch commented on src/Widgets/Checkout/CancelPaymentWidget.php
> +            ->withCategory(WidgetCategories::BASKET)
```suggestion
            ->withCategory(WidgetCategories::CHECKOUT)
```

2019-11-18 15:10 UTC, felixdausch commented on src/Widgets/Checkout/CancelPaymentWidget.php
> +        $select = $settings->createSelect("buttonSize")
see https://github.com/plentymarkets/plugin-ceres/pull/1676

2019-11-18 15:10 UTC, felixdausch commented on src/Widgets/Checkout/CancelPaymentWidget.php
> +        $select->withListBoxValues(
```suggestion
        ->withListBoxValues(
```

2019-11-18 15:10 UTC, felixdausch commented on src/Widgets/Checkout/GtcCheckWidget.php
> +            ->withPosition(400)
`maxPerPage: 1` fehlt!

2019-11-18 15:10 UTC, felixdausch commented on src/Widgets/Checkout/PlaceOrderWidget.php
> +        $select = $settings->createSelect("buttonSize")
see https://github.com/plentymarkets/plugin-ceres/pull/1676

2019-11-18 16:43 UTC, felixdausch approved these changes

2019-11-18 16:50 UTC, merged