ADD PriceFilterWidget
plentymarkets/plugin-ceres pull request #1670
Opened 2019-11-18 12:18 UTC by cjohannsen

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-11-18 12:26 UTC, fmutschler submitted a review, later dismissed

2019-11-18 12:26 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +priceFilterLabel = "Filter für Preise"
```suggestion
priceFilterLabel = "Preisfilter"
```

2019-11-18 12:26 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +priceFilterLabel = "Filter for prices"
```suggestion
priceFilterLabel = "Price filter"
```

2019-11-18 15:35 UTC, stentrop requested changes
geht aktuell nicht

2019-11-18 16:09 UTC, cjohannsen commented
> geht aktuell nicht

done https://github.com/plentymarkets/plugin-ceres/pull/1670/commits/17f57765f7bb98487b17f5586b58cded59da083e

2019-11-19 08:23 UTC, stentrop approved these changes

2019-11-19 08:23 UTC, merged