ADD navgation tree faker
plentymarkets/plugin-ceres pull request #1729
Opened 2019-11-29 13:53 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-12-03 14:53 UTC, Tim-M-S approved these changes

2019-12-04 07:14 UTC, stentrop requested changes

2019-12-04 07:14 UTC, stentrop commented on src/Widgets/Navigation/NavigationTreeWidget.php
> +        {
PSR-2 Codestyling beachten

Leerzeichen nach if
Leerzeichen nach condition Klammer und dann geschweifte Klammer nicht in eine extra Zeile

2019-12-04 07:14 UTC, stentrop requested changes

2019-12-04 07:14 UTC, stentrop commented on src/Widgets/Header/NavigationWidget.php
> +        {
PSR-2 Codestyling beachten

Leerzeichen nach if
Leerzeichen nach condition Klammer und dann geschweifte Klammer nicht in eine extra Zeile

2019-12-04 13:53 UTC, stentrop approved these changes

2019-12-04 14:01 UTC, merged