ADD sb item search
plentymarkets/plugin-ceres pull request #1737
Opened 2019-12-03 12:54 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-12-03 21:00 UTC, Tim-M-S requested changes

2019-12-03 21:00 UTC, Tim-M-S commented on resources/views/Category/Item/CategoryItem.twig
> +    {% endif %}
ersetzbar durch {% set listType = isSearch ? "itemsearch" : "categoryitem" %}

2019-12-04 12:26 UTC, stentrop requested changes

2019-12-04 12:26 UTC, stentrop commented on src/ShopBuilder/Handler/ShopBuilderSettingsHandler.php
> +        return in_array( RouteConfig::SEARCH, RouteConfig::getEnabledRoutes());
```suggestion
        return in_array(RouteConfig::SEARCH, RouteConfig::getEnabledRoutes());
```

2019-12-04 12:26 UTC, stentrop commented on src/ShopBuilder/Handler/ShopBuilderSettingsHandler.php
> +    public function readRouting_searchEnableRoute()
```suggestion
    public function readRouting_searchEnableRoute(): bool
```

2019-12-04 12:26 UTC, stentrop commented on src/ShopBuilder/Handler/ShopBuilderSettingsHandler.php
> +    public function writeRouting_searchEnableRoute($enableSearchRoute)
```suggestion
    public function writeRouting_searchEnableRoute($enableSearchRoute): string
```

2019-12-04 14:00 UTC, stentrop approved these changes

2019-12-04 14:14 UTC, Tim-M-S approved these changes

2019-12-04 14:25 UTC, merged