BackgroundWidget - the placeholder will not longer overlap with the dropzone
plentymarkets/plugin-ceres pull request #1798
Opened 2019-12-16 15:39 UTC by cjohannsen

### All changes meet the following requirements
- ~Changelog entry was added~
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-12-16 15:51 UTC, lks-mtzn commented on resources/views/Widgets/Common/BackgroundWidget.twig
> +            <div>
```suggestion
            <div class="widget-placeholder">
```

2019-12-16 17:22 UTC, felixdausch requested changes

2019-12-16 17:22 UTC, felixdausch commented on resources/views/Widgets/Common/BackgroundWidget.twig
> +            {% if colorPalette != "custom" and colorPalette != "none" %} bg-{{ colorPalette | default("none") }}{% endif %}"
Ich würde bereits beim Initialisieren von `colorPalette` einen default-Wert zuweisen. So hebelst du deine eigene Abfrage aus und wenn colorPalette leer ist, wird die Klasse `bg-none` ergänzt, die du eigentlich verhindern möchtest.

2019-12-16 17:32 UTC, cjohannsen commented on resources/views/Widgets/Common/BackgroundWidget.twig
> +            {% if colorPalette != "custom" and colorPalette != "none" %} bg-{{ colorPalette | default("none") }}{% endif %}"
👍 done: https://github.com/plentymarkets/plugin-ceres/pull/1798/commits/87c282f65912d32f51ce447417ed90f48a1e75ec

2019-12-17 08:15 UTC, felixdausch approved these changes

2019-12-17 10:19 UTC, merged