FIX basket item property price design
plentymarkets/plugin-ceres pull request #187
Opened 2017-10-24 08:00 UTC by Dominik2809

@Strean1337 
@lks-mtzn

2017-10-24 08:45 UTC, Sebsta13 requested changes

2017-10-24 08:45 UTC, Strean1337 commented on resources/views/Basket/Components/BasketListItem_large.twig
> +            <strong class="col-xs-6 col-sm-5">${basketItem.variation.data.properties | propertySurcharge parseInt(property.propertyId) | currency} pro Artikel</strong>
kannst du doch so nicht machen.. Das muss i18n

2017-10-24 08:45 UTC, Strean1337 commented on resources/views/Basket/Components/BasketListItem_small.twig
> +            <span>pro Artikel</span>
hier auch

2017-10-25 11:32 UTC, Dominik2809 commented on resources/views/Basket/Components/BasketListItem_small.twig
> +            <span>pro Artikel</span>
fixed @Strean1337

2017-10-25 14:06 UTC, Sebsta13 approved these changes

2017-10-25 14:07 UTC, merged