Refactor pages having white backgrounds
plentymarkets/plugin-ceres pull request #1870
Opened 2020-01-13 10:44 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2020-01-13 15:34 UTC, cjohannsen requested changes

2020-01-13 15:34 UTC, cjohannsen commented on src/Widgets/Presets/WishListPreset.php
> +        $this->createBackground($preset);
Oberhalb der Überschrift ist kein Freiraum und der Container mit der Hintergrund-Farbe hat das Padding von 30px verloren. Dies wurde vorher über folgenden Selektor erzeugt:

![Uploading Bildschirmfoto 2020-01-13 um 16.15.28.png…]()

2020-01-13 15:34 UTC, cjohannsen commented on src/Widgets/Presets/DefaultMyAccountPreset.php
> +        $this->createBackground($this->preset);
Ich weiß nicht ob es an diesem Preset liegt (vermutlich nicht), aber die oberen Inputs sehen sehr kaputt aus:

![Bildschirmfoto 2020-01-13 um 16 18 04](https://user-images.githubusercontent.com/22615263/72267420-54eea200-3620-11ea-910c-37f450ffd368.png)

2020-01-13 15:34 UTC, cjohannsen commented on src/Widgets/Presets/DefaultContactPreset.php
> +    use HasWhiteBackground;
Vermutlich liegt es wieder am CSS, trotzdem erwähnenswert:

![Bildschirmfoto 2020-01-13 um 16 22 08](https://user-images.githubusercontent.com/22615263/72267725-dc3c1580-3620-11ea-8beb-52724091c8ff.png)

2020-01-13 15:34 UTC, cjohannsen commented on src/Widgets/Presets/DefaultCheckoutPreset.php
> +    use HasWhiteBackground;
Die Höhe vom Hintergrundwidget ist nicht korrekt, der Inhalt ist scrollbar:

![Uploading Bildschirmfoto 2020-01-13 um 16.24.25.png…]()

2020-01-13 15:34 UTC, cjohannsen commented on resources/views/MyAccount/MyAccountView.twig
> +            <div class="page-content myaccount container-max mb-5 mt-3 pt-3 bg-white">
Hier muss noch margin hin, da der Inhalt sonst oben an der Navigation klebt

2020-01-13 15:34 UTC, cjohannsen commented on resources/scss/ceres/common/_visibility.scss
> +.hidden {
gibt es diese Klasse nicht schon von Bootstrap?

2020-01-13 16:07 UTC, felixdausch commented on src/Widgets/Presets/WishListPreset.php
> +        $this->createBackground($preset);
Der Abstand wird jetzt über das BackgroundWidget im trait gesetzt.

2020-01-13 16:07 UTC, felixdausch commented on src/Widgets/Presets/DefaultMyAccountPreset.php
> +        $this->createBackground($this->preset);
War ein anderer Fehler. Ist gefixed

2020-01-13 16:07 UTC, felixdausch commented on src/Widgets/Presets/DefaultContactPreset.php
> +    use HasWhiteBackground;
anderer Fehler... Gefixed.

2020-01-13 16:07 UTC, felixdausch commented on src/Widgets/Presets/DefaultCheckoutPreset.php
> +    use HasWhiteBackground;
anderer Fehler... Gefixed.

2020-01-13 16:08 UTC, felixdausch commented on resources/views/MyAccount/MyAccountView.twig
> +            <div class="page-content myaccount container-max mb-5 mt-3 pt-3 bg-white">
Hat doch `mt-3`?

2020-01-13 16:08 UTC, felixdausch commented on resources/scss/ceres/common/_visibility.scss
> +.hidden {
Ja macht es, aber nicht im Rahmen dieses Umbaus.

2020-01-14 10:09 UTC, cjohannsen requested changes

2020-01-14 10:09 UTC, cjohannsen commented on src/Widgets/Presets/DefaultBasketPreset.php
> +    use HasWhiteBackground;
Mir ist noch aufgefallen, dass im Warenkorb unten der Abstand zum Footer fehlt:

_lokal_
![Bildschirmfoto 2020-01-14 um 11 07 36](https://user-images.githubusercontent.com/22615263/72334845-4b1b7c00-36be-11ea-8c6a-026a572c8b87.png)


_Ceres demo_
![Bildschirmfoto 2020-01-14 um 11 08 57](https://user-images.githubusercontent.com/22615263/72334876-54a4e400-36be-11ea-87c9-6f39b580aef7.png)

2020-01-14 10:13 UTC, cjohannsen commented on src/Widgets/Presets/WishListPreset.php
> +        $this->createBackground($preset);
Ich habe den Inhalt neu erstellt mit dem Preset und es sieht weiterhin so aus im Frontend:

![Bildschirmfoto 2020-01-14 um 11 12 31](https://user-images.githubusercontent.com/22615263/72335181-db59c100-36be-11ea-85c1-73215d41082f.png)

2020-01-14 10:15 UTC, cjohannsen commented on resources/views/MyAccount/MyAccountView.twig
> +            <div class="page-content myaccount container-max mb-5 mt-3 pt-3 bg-white">
jetzt sieht es richtig aus bei mir 👍

2020-01-14 10:26 UTC, cjohannsen approved these changes

2020-01-14 10:26 UTC, merged