Style/basket item
plentymarkets/plugin-ceres pull request #1890
Opened 2020-01-17 10:37 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2020-01-19 09:12 UTC, JVolke commented on resources/scss/ceres/views/Templates/BasketItemList/_basket-list-item.scss
> +        height: 41px;
Hier muss noch rein !important rein, da ansonsten die Klasse h-100 das wieder überschreibt

2020-01-20 14:12 UTC, Tim-M-S reviewed
![Bildschirmfoto 2020-01-20 um 15 10 31](https://user-images.githubusercontent.com/11943448/72732899-11071a00-3b97-11ea-812a-6ad061b8d53e.png)

Auf dem WishListItem.twig fehlen einige Margins

2020-01-20 14:12 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/CategoryListItem/_category-list-item.scss
> +}
missing newline

2020-01-20 14:12 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/BasketItemList/_basket-list-item.scss
> +            margin: 0 10px;
was bringt die margin-left die hier noch dazu kommt?

2020-01-20 14:12 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/Item/_quantity-input.scss
> +        margin-left: auto;
Wofür brauchen wir das?

2020-01-20 14:31 UTC, Tim-M-S reviewed
![Bildschirmfoto 2020-01-20 um 15 31 00](https://user-images.githubusercontent.com/11943448/72734409-e7032700-3b99-11ea-95e2-cb8af85d5878.png)

Auch auf der Retourseite fehlen Margins

2020-01-20 14:57 UTC, Tim-M-S reviewed
Retour sieht komisch auf sm aus
![Bildschirmfoto 2020-01-20 um 15 56 20](https://user-images.githubusercontent.com/11943448/72736160-7e1dae00-3b9d-11ea-9744-ef581845fbb7.png)

2020-01-20 16:18 UTC, Tim-M-S reviewed
![Bildschirmfoto 2020-01-20 um 17 17 21](https://user-images.githubusercontent.com/11943448/72741862-cd1d1080-3ba8-11ea-8755-b5952b658ba1.png)
PurchasedItemsWidget auf Orderconfirmation sieht auf xs komisch aus

2020-01-23 16:10 UTC, Tim-M-S requested changes
![Bildschirmfoto 2020-01-23 um 17 10 12](https://user-images.githubusercontent.com/11943448/73001773-43b54a80-3e03-11ea-82a2-b8906b86b296.png)
Retour auf xs viewport

2020-01-30 10:36 UTC, Tim-M-S approved these changes

2020-01-30 10:38 UTC, merged