Refactor/category item
plentymarkets/plugin-ceres pull request #1928
Opened 2020-01-29 17:38 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2020-02-03 10:02 UTC, felixdausch requested changes

2020-02-03 10:02 UTC, felixdausch commented on resources/js/src/app/components/basket/AddToBasket.vue
> +                    <span>{{ $translate("Ceres::Template.singleItemAddToBasket") }}</span>
Wird hier der `span`-Tag benötigt? Ansonsten bitte nur den Text ausgeben. Spart wieder einen Knoten im DOM

2020-02-03 10:02 UTC, felixdausch commented on resources/js/src/app/components/basket/AddToBasket.vue
> +                    <span>{{ $translate("Ceres::Template.itemShowItem") }}</span>
s.o. kein span, wenn nicht notwendig...

2020-02-03 13:18 UTC, Tim-M-S commented on resources/js/src/app/components/basket/AddToBasket.vue
> +                    <span>{{ $translate("Ceres::Template.singleItemAddToBasket") }}</span>
done

2020-02-03 13:18 UTC, Tim-M-S commented on resources/js/src/app/components/basket/AddToBasket.vue
> +                    <span>{{ $translate("Ceres::Template.itemShowItem") }}</span>
done

2020-02-04 14:50 UTC, felixdausch approved these changes

2020-02-04 14:59 UTC, felixdausch requested changes

2020-02-04 14:59 UTC, felixdausch commented on resources/js/src/app/components/itemList/ItemStoreSpecial.vue
> +        <span v-if="label.length" class="badge shadow-sm" :class="tagClass">
`.shadow-sm` führt leider optisch nicht zum selben Ergebnis wie auf beta

2020-02-04 14:59 UTC, felixdausch commented
Der Warenkorb-Button ist auf beta outlined, hier jetzt nicht mehr:
![Bildschirmfoto 2020-02-04 um 15 54 47](https://user-images.githubusercontent.com/7404578/73756124-603c7580-4767-11ea-9d63-d9227a852c76.png)
![Bildschirmfoto 2020-02-04 um 15 54 33](https://user-images.githubusercontent.com/7404578/73756130-629ecf80-4767-11ea-9ed9-ed260644191b.png)

2020-02-04 17:04 UTC, Tim-M-S commented on resources/js/src/app/components/itemList/ItemStoreSpecial.vue
> +        <span v-if="label.length" class="badge shadow-sm" :class="tagClass">
done

2020-02-04 17:18 UTC, felixdausch approved these changes

2020-02-04 17:19 UTC, merged