Refactor/item list sort pagination
plentymarkets/plugin-ceres pull request #1930
Opened 2020-01-30 15:24 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2020-02-04 13:15 UTC, cjohannsen requested changes

2020-02-04 13:15 UTC, cjohannsen commented on resources/views/MyAccount/Components/OrderHistoryList.twig
> +        <div class="row history-pagination mt-3 mb-2" v-if="orderList.totalsCount > ordersPerPage">
Du hast die Klasse .history-pagination gelöscht, dann kann die auch aus dem Markup entfernt werden. An folgenden Stellen konnte ich die Klasse finden:

![Bildschirmfoto 2020-02-04 um 14 10 20](https://user-images.githubusercontent.com/22615263/73747623-1b5d1280-4758-11ea-8356-e2cbe6fbffd9.png)

2020-02-04 13:15 UTC, cjohannsen commented on resources/scss/ceres/views/MyAccount/_my-account.scss
> -.history-pagination {
Durch das entfernen dieser Klasse klebt die Pagination direkt an der grauen Linie. Entweder sollte die Klasse dann an den 4 Stellen auch entfernt werden und durch eine Bootstrap Klasse ersetzt werden (mt-3 kommt nahezu hin), oder du lässt sie da.

Dein Branch:
![Bildschirmfoto 2020-02-04 um 14 12 12](https://user-images.githubusercontent.com/22615263/73747884-a5a57680-4758-11ea-9005-20460b47c12b.png)

Beta5:
![Bildschirmfoto 2020-02-04 um 14 13 43](https://user-images.githubusercontent.com/22615263/73747893-ac33ee00-4758-11ea-833d-1e7cc3213a65.png)

2020-02-05 09:09 UTC, Tim-M-S commented on resources/views/MyAccount/Components/OrderHistoryList.twig
> +        <div class="row history-pagination mt-3 mb-2" v-if="orderList.totalsCount > ordersPerPage">
done

2020-02-05 09:09 UTC, Tim-M-S commented on resources/scss/ceres/views/MyAccount/_my-account.scss
> -.history-pagination {
done

2020-02-05 09:40 UTC, cjohannsen approved these changes

2020-02-05 10:30 UTC, merged