Fix/stylelint errors
plentymarkets/plugin-ceres pull request #1956
Opened 2020-02-07 08:53 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2020-02-10 15:26 UTC, Tim-M-S requested changes

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/common/_buttons.scss
> +            border-radius: 0 !important; // stylelint-disable-line
```suggestion
            border-radius: 0 !important; // stylelint-disable-line declaration-no-important
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/components/_anicon.scss
> +        transition: .3s; // stylelint-disable-line property-blacklist
```suggestion
        @include transition(.3s);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/components/_anicon.scss
> +            transition: .3s; // stylelint-disable-line property-blacklist
```suggestion
            @include transition(.3s);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/components/_anicon.scss
> +            transition: .3s; // stylelint-disable-line property-blacklist
```suggestion
            @include transition(.3s);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/components/_featured-category.scss
> +        @include transition(all 300ms);
```suggestion
        @include transition(all .3s);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/ToggleCategoryListView/_toggle-list-view.scss
> -.toggle-list-view {
Hier kann dann ja wahrscheinlich auch der Teil aus der main.js entfernt werden:
```
    const $toggleListView = $(".toggle-list-view");

    $toggleListView.on("click", function(evt)
    {
        evt.preventDefault();

        // toggle it's own state
        $toggleListView.toggleClass("grid");

        // toggle internal style of thumbs
        $(".product-list, .cmp-product-thumb").toggleClass("grid");
    });
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Category/_category-list-controls.scss
> +        .expand-nav {
Muss in category-list-controls.scss dann auch umbenannt werden

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/Hero/_component-hero.scss
> -.cmp-hero {
deprecated

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +                background: $gray-100; // stylelint-disable-line selector-no-qualifying-type
```suggestion
                background-color: $gray-100; // stylelint-disable-line selector-no-qualifying-type
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +            .row div span:first-child { // stylelint-disable-line
```suggestion
            .row div span:first-child { // stylelint-disable-line selector-max-compound-selectors
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +                span:first-child { // stylelint-disable-line
```suggestion
                span:first-child { // stylelint-disable-line selector-max-compound-selectors
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +            .row div:first-child { // stylelint-disable-line
```suggestion
            .row div:first-child { // stylelint-disable-line selector-max-compound-selectors
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/OrderItem/_order-item.scss
> +        @include transition(all 300ms);
```suggestion
        @include transition(all .3s);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/views/Templates/OrderItem/_order-item.scss
> +        @include transition(max-height 300ms);
```suggestion
        @include transition(max-height .3s);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/widgets/Common/_image-carousel-widget.scss
> +                @include transition(300ms all ease);
```suggestion
                @include transition(.3s all ease);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/widgets/Common/_image-carousel-widget.scss
> +            @include transition(300ms all ease);
```suggestion
            @include transition(.3s all ease);
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/widgets/Helper/_base-widget.scss
> +    left: calc(-1 * (100vw - 100%) / 2) !important; // stylelint-disable-line
```suggestion
    left: calc(-1 * (100vw - 100%) / 2) !important; // stylelint-disable-line function-blacklist
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/widgets/Helper/_base-widget.scss
> +    left: calc(-1 * (100vw - 100%) / 2) !important; // stylelint-disable-line
```suggestion
    left: calc(-1 * (100vw - 100%) / 2) !important; // stylelint-disable-line function-blacklist
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/widgets/Helper/_base-widget.scss
> +        width: calc(100vw + 30px) !important; // stylelint-disable-line
```suggestion
        width: calc(100vw + 30px) !important; // stylelint-disable-line function-blacklist
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/widgets/Helper/_widget-appearance.scss
> +                &.active .page-link { // stylelint-disable-line
```suggestion
                &.active .page-link { // stylelint-disable-line selector-max-class
```

2020-02-10 15:26 UTC, Tim-M-S commented on resources/scss/ceres/widgets/Category/_item-grid-widget.scss
> -
![Bildschirmfoto 2020-02-10 um 16 23 44](https://user-images.githubusercontent.com/11943448/74162919-d8041780-4c21-11ea-9c6e-b58e33136e10.png)
Das ist mit Standard Paddings&Margins
Man sollte dann auch in der category-list-item.scss diese Zeile entfernen
`margin-bottom: $grid-gutter-width / 2;`

2020-02-21 08:39 UTC, felixdausch commented on resources/scss/ceres/common/_buttons.scss
> +            border-radius: 0 !important; // stylelint-disable-line
👍

2020-02-21 08:40 UTC, felixdausch commented on resources/scss/ceres/components/_anicon.scss
> +        transition: .3s; // stylelint-disable-line property-blacklist
Das habe ich in dem Fall bewusst nicht über das mixin gelöst, da der ganze Aufwand für das Such-Icon nur dazu betrieben wurde, um die Animation von der Lupe zum X hinzubekommen. In diesem speziellen Fall macht es also keinen sinn, die Transition per Variable zu deaktiveren

2020-02-21 08:41 UTC, felixdausch commented on resources/scss/ceres/components/_anicon.scss
> +            transition: .3s; // stylelint-disable-line property-blacklist
Hier dasselbe => Veränderungen durch Variablen machen hier keinen Sinn.

2020-02-21 08:42 UTC, felixdausch commented on resources/scss/ceres/components/_featured-category.scss
> +        @include transition(all 300ms);
👍

2020-02-21 08:43 UTC, felixdausch commented on resources/scss/ceres/views/Templates/ToggleCategoryListView/_toggle-list-view.scss
> -.toggle-list-view {
👍

2020-02-21 08:44 UTC, felixdausch commented on resources/scss/ceres/views/Category/_category-list-controls.scss
> +        .expand-nav {
👍

2020-02-21 08:45 UTC, felixdausch commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +                background: $gray-100; // stylelint-disable-line selector-no-qualifying-type
👍

2020-02-21 08:46 UTC, felixdausch commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +            .row div span:first-child { // stylelint-disable-line
👍

2020-02-21 08:46 UTC, felixdausch commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +                span:first-child { // stylelint-disable-line
👍

2020-02-21 08:47 UTC, felixdausch commented on resources/scss/ceres/views/Templates/OrderItem/_order-history-list.scss
> +            .row div:first-child { // stylelint-disable-line
👍

2020-02-21 08:59 UTC, felixdausch commented on resources/scss/ceres/widgets/Helper/_widget-appearance.scss
> +                &.active .page-link { // stylelint-disable-line
👍

2020-02-21 09:03 UTC, felixdausch commented on resources/scss/ceres/widgets/Helper/_base-widget.scss
> +        width: calc(100vw + 30px) !important; // stylelint-disable-line
👍

2020-02-21 14:53 UTC, felixgehrmann commented
<img width="445" alt="Bildschirmfoto 2020-02-21 um 15 51 57" src="https://user-images.githubusercontent.com/52066685/75044638-48345800-54c2-11ea-9046-e31c05eb1271.png">

Tag ist hinter dem Bild, fehlt da ein z-index?

2020-02-21 14:55 UTC, felixgehrmann commented
<img width="445" alt="Bildschirmfoto 2020-02-21 um 15 51 57" src="https://user-images.githubusercontent.com/52066685/75044830-8e89b700-54c2-11ea-8260-b3599dda3e82.png">

Tag hinter dem Item-Bild. Interessanterweise nur bei diesem Tag. Problem scheint der z-Index zu sein.

2020-02-21 15:05 UTC, felixgehrmann commented
![Bildschirmfoto 2020-02-21 um 16 03 18](https://user-images.githubusercontent.com/52066685/75045558-c6ddc500-54c3-11ea-9892-0887068f9826.png)

margin-bottom missing?

2020-02-21 15:12 UTC, felixgehrmann approved these changes
Stylelint errors sind fixed. 
Mir sind zwei Sachen aufgefallen, wo ich mir nicht sicher war, ob mir das noch nicht aufgefallen ist, oder ob das hier reingekommen ist.

2020-02-21 15:24 UTC, merged