Fix/myaccount styling
plentymarkets/plugin-ceres pull request #1966
Opened 2020-02-13 12:51 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2020-02-17 08:40 UTC, felixdausch requested changes

2020-02-17 08:40 UTC, felixdausch commented on resources/views/MyAccount/Components/BankDataSelect.twig
> +                            <p class="text-muted small font-italic pt-3">{{ trans("Ceres::Template.myAccountBankNoBankData") }}</p>
Warum?

2020-02-17 08:40 UTC, felixdausch commented on src/Widgets/MyAccount/LogoutButtonWidget.php
> +        $settings->createAppearance();
Auch hier: Warum? Der Button ist im Standard rot, folglich macht der default-Wert hier Sinn?

2020-02-17 12:15 UTC, Tim-M-S commented on resources/views/MyAccount/Components/BankDataSelect.twig
> +                            <p class="text-muted small font-italic pt-3">{{ trans("Ceres::Template.myAccountBankNoBankData") }}</p>
Weil es bei Rechnungsadressen und Lieferadressen auch nicht ist. Lässt sich ja nichtmal über die Mehrsprachigkeit steuern.
![Bildschirmfoto 2020-02-17 um 13 13 40](https://user-images.githubusercontent.com/11943448/74652975-7bf04480-5187-11ea-946d-f76706be6d08.png)

2020-02-17 12:29 UTC, Tim-M-S commented on src/Widgets/MyAccount/LogoutButtonWidget.php
> +        $settings->createAppearance();
Dann müssen wir das bei ein paar Widgets noch nachbessern

2020-03-02 16:09 UTC, felixdausch approved these changes

2020-03-02 16:34 UTC, merged