feature/beta/items_sets/ add new widgetTypes "setitem, setonly"
plentymarkets/plugin-ceres pull request #2044
Opened 2020-03-11 10:26 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2020-03-11 12:53 UTC, felixdausch commented on shopBuilder.json
> +        "itemset":      ["static", "structure", "default", "item", "setitem", "setonly"],
Ist es vielleicht verständlicher, den Typ "item" für SingleItem und SetItem zu verwenden und dann "setitem" für Widgets, die ausschließlich für Sets und "singleitem" für Widgets, die ausschließlich für Nicht-Sets gedacht sind, zu verwenden.
Dann müsste man alle aktuellen Item-Widgets vom Typ auf "singleitem" ändern und diejenigen auf "item" zurückändern, die für beides gelten sollen.

2020-03-11 13:45 UTC, Tim-M-S commented on shopBuilder.json
> +        "itemset":      ["static", "structure", "default", "item", "setitem", "setonly"],
done

2020-03-11 17:01 UTC, felixdausch requested changes

2020-03-11 17:01 UTC, felixdausch commented on shopBuilder.json
> +        "itemset":      ["static", "structure", "default", "item", "itemcontent"],
```suggestion
        "itemset":      ["static", "structure", "default", "item", "itemcontent", "setitem"],
```

2020-03-11 17:01 UTC, felixdausch commented on src/Widgets/Helper/WidgetTypes.php
> +    const ITEM_CONTENT = 'itemcontent';
```suggestion
    const SINGLE_ITEM = 'singleitem';  // only available on contents of type 'singleitem' 
    const SET_ITEM = 'setitem';  // only available on contents of type 'setitem'
    const SET_COMPONENT = 'setcomponent'; // available on contents of type 'singleitem' or inside of each item set component, but not in contents of type 'itemset'
    const ITEM_CONTENT = 'itemcontent'; // available on contents of type 'singleitem' or 'setitem' but not inside of each item set component
```

2020-03-12 08:51 UTC, felixdausch approved these changes

2020-03-12 10:51 UTC, merged