FIX empty shopbuilder headers
plentymarkets/plugin-ceres pull request #2266
Opened 2020-06-05 15:09 UTC by cjohannsen

- TwigStyleScriptTagFilter.php - scrip and style tags are not longer replaced via regex, because it causes PREG_BACKTRACK_LIMIT_ERROR

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io

2020-06-10 15:35 UTC, stentrop reviewed
Preview Badge kommt doppelt raus

2020-06-18 16:07 UTC, cjohannsen commented
> Preview Badge kommt doppelt raus

fkxed

2020-06-19 07:09 UTC, stentrop requested changes

2020-06-19 07:09 UTC, stentrop commented on src/Extensions/TwigStyleScriptTagFilter.php
> +            $trim_off_end = (strrpos($content,'</body>')) - strlen($content);
camelCase

2020-06-19 07:09 UTC, stentrop commented on src/Extensions/TwigStyleScriptTagFilter.php
> +            $trim_off_end = (strrpos($content,'</body>')) - strlen($content);
camelCase

2020-06-19 07:21 UTC, stentrop requested changes
Vorher:
<img width="1249" alt="Bildschirmfoto 2020-06-19 um 09 12 12" src="https://user-images.githubusercontent.com/13133283/85107380-28156b00-b20e-11ea-88f6-b4e0d2dccb1b.png">

Sobald er ein script tag entfernt:
<img width="1543" alt="Bildschirmfoto 2020-06-19 um 09 19 57" src="https://user-images.githubusercontent.com/13133283/85107426-3a8fa480-b20e-11ea-9e2a-bc8f75b8ebdf.png">


Achte auf das Wort Büro in der Navigation

2020-06-19 07:30 UTC, cjohannsen commented on src/Extensions/TwigStyleScriptTagFilter.php
> +            $trim_off_end = (strrpos($content,'</body>')) - strlen($content);
done

2020-06-19 07:30 UTC, cjohannsen commented on src/Extensions/TwigStyleScriptTagFilter.php
> +            $trim_off_end = (strrpos($content,'</body>')) - strlen($content);
done

2020-07-08 09:10 UTC, stentrop approved these changes

2020-07-08 09:14 UTC, merged