use setting in my account config again
plentymarkets/plugin-ceres pull request #2361
Opened 2020-08-26 16:15 UTC by felixgehrmann

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io

2020-09-04 15:19 UTC, felixdausch requested changes, later dismissed

2020-09-04 15:19 UTC, felixdausch commented on resources/views/MyAccount/Components/OrderHistory.twig
> +                                            {% if returnOrder.isReturnable and allowReturns %}
```suggestion
                                            {% if returnOrder.isReturnable and ceresConfig.myAccount.orderReturnActive %}
```

Die `PluginConfig`-Klasse regelt bei boolean-Flags mehrere Fälle, da je nach Konstellation `"true"` oder `"1"` oder `1` in der Tabelle gespeichert werden.

2020-09-04 15:19 UTC, felixdausch commented on resources/views/MyAccount/MyAccountView.twig
> +    {% set isReturnActive = config("Ceres.my_account.order_return_active") %}
```suggestion
    {% set isReturnActive = ceresConfig.myAccount.orderReturnActive %}
```

2020-09-04 15:19 UTC, felixdausch commented on resources/views/MyAccount/MyAccountView.twig
> +                    :is-return-active="{{ isReturnActive }}"
```suggestion
                    :is-return-active="{{ isReturnActive | json_encode }}"
```
wird dann doch wieder benötigt, wenn du oben auf das globale `ceresConfig`-Objekt zugreifst.

2020-09-09 10:11 UTC, maxiroellplenty approved these changes

2020-09-09 10:15 UTC, merged