Feature/recapcha newsletter
plentymarkets/plugin-ceres pull request #2496
Opened 2020-11-04 10:25 UTC by maxiroellplenty

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io

2020-11-16 20:13 UTC, felixdausch requested changes, later dismissed

2020-11-16 20:13 UTC, felixdausch commented on resources/js/src/app/components/newsletter/NewsletterInput.vue
> +            loadRecapcha: true
ist das jemals `false`?

2020-11-16 20:13 UTC, felixdausch commented on resources/js/src/app/components/newsletter/NewsletterInput.vue
> +        <recaptcha v-if="!!googleRecaptchaApiKey && loadRecapcha"></recaptcha>
```suggestion
        <recaptcha v-if="!!App.config.global.googleRecaptchaApiKey && loadRecapcha"></recaptcha>
```

2020-11-16 20:13 UTC, felixdausch commented on resources/js/src/app/components/newsletter/NewsletterInput.vue
> +            loadRecapcha: true
Falls es noch benötigt wird, hast du hier noch eine Typo: es fehlt das "t" in "loadRecap**t**cha".

2020-11-16 20:13 UTC, felixdausch commented on resources/js/src/app/components/newsletter/NewsletterInput.vue
> +            googleRecaptchaApiKey: App.config.global.googleRecaptchaApiKey,
Wenn sich der Wert nicht ändert, kannst du im Template auch direkt auf den Config-Wert zugreifen.

2020-11-16 20:13 UTC, felixdausch commented on resources/js/src/app/components/newsletter/NewsletterInput.vue
> +            executeReCaptcha(this.$refs.newsletterForm)
die Referenz ist hier nicht nötig. Du kannst auch direkt das root Element über `this.$el` in die Funktion geben.

2020-11-16 20:13 UTC, felixdausch commented on resources/js/src/app/components/newsletter/NewsletterInput.vue
> +                const recaptchaId = this.$refs.newsletterForm.querySelector("[data-recaptcha]");
```suggestion
                const recaptchaId = this.$el.querySelector("[data-recaptcha]");
```
s.o

2020-11-24 08:15 UTC, Tim-M-S approved these changes

2020-11-24 10:10 UTC, merged