Feature/contact upload widget
plentymarkets/plugin-ceres pull request #2636
Opened 2021-02-02 17:10 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io

2021-02-03 07:47 UTC, stentrop requested changes

2021-02-03 07:47 UTC, stentrop commented on resources/js/src/app/store/modules/ContactFormModule.js
> +        formData.append("rcaptchaToken", recaptchaToken);
```suggestion
        formData.append("recaptchaToken", recaptchaToken);
```

2021-02-03 09:02 UTC, stentrop submitted a review, later dismissed

2021-02-03 09:02 UTC, stentrop commented on resources/js/src/app/store/modules/ContactFormModule.js
> +                                response.error.message = response.error.message || TranslationService.translate("Ceres::Template.contactFileUploadFail");
Hier gibt es kein response

2021-02-03 09:39 UTC, lks-mtzn commented on resources/js/src/app/store/modules/ContactFormModule.js
> +                            (error) =>
```suggestion
                            (response) =>
```

2021-02-03 09:47 UTC, Tim-M-S commented on resources/js/src/app/store/modules/ContactFormModule.js
> +                            (error) =>
done

2021-02-03 09:47 UTC, Tim-M-S commented on resources/js/src/app/store/modules/ContactFormModule.js
> +        formData.append("rcaptchaToken", recaptchaToken);
done

2021-02-03 10:00 UTC, Tim-M-S commented on resources/js/src/app/store/modules/ContactFormModule.js
> +                                response.error.message = response.error.message || TranslationService.translate("Ceres::Template.contactFileUploadFail");
done

2021-02-09 09:56 UTC, fmutschler submitted a review, later dismissed

2021-02-09 13:30 UTC, cjohannsen approved these changes

2021-02-09 13:33 UTC, merged