Feature/account informations
plentymarkets/plugin-ceres pull request #264
Opened 2018-01-16 16:17 UTC by Strean1337

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested

@plentymarkets/ceres-io

2018-01-17 08:45 UTC, felixdausch requested changes
Muss optisch überarbeitet werden.
Texte bitte von @dbohla übersetzen lassen.

2018-01-17 12:26 UTC, dbohla commented
@felixdausch:  Texte sind geprüft und übersetzt.

2018-01-29 13:36 UTC, cjohannsen approved these changes

2018-02-02 09:55 UTC, lks-mtzn requested changes

2018-02-02 09:55 UTC, lks-mtzn commented on resources/views/PageDesign/Components/Popper.twig
> +				<!-- Element to trigger popper -->
Mach mal hieraus twig Kommentare dann werden die nicht mitgeschickt.

2018-02-02 09:55 UTC, lks-mtzn commented on resources/js/src/app/components/pageDesign/Popper.js
> +    data: function()
data()

2018-02-02 09:55 UTC, lks-mtzn commented on resources/js/src/app/components/pageDesign/Popper.js
> +        "template",
Änder die props noch mal auf das Format. https://vuejs.org/v2/guide/components.html#Prop-Validation

2018-02-02 10:08 UTC, lks-mtzn approved these changes

2018-02-02 10:10 UTC, Strean1337 commented
@felixdausch könntest du ggf. auch nochmal drüber schauen?

2018-02-02 15:15 UTC, felixdausch requested changes

2018-02-02 15:15 UTC, felixdausch commented on resources/scss/ceres/components/_popper.scss
> +    text-align: start;
`text-align: start` ist kein valides css

2018-02-02 15:15 UTC, felixdausch commented on resources/scss/ceres/components/_popper.scss
> +    border: 1px solid rgba(0,0,0,.2);
bitte `$popup-border-*`-Variablen verbauen (siehe `_variables.scss`)

2018-02-02 15:15 UTC, felixdausch commented on resources/scss/ceres/components/_popper.scss
> +	&[x-placement^="top"] {
gemeinsame eigenschaften können unter einem gemeinsamen Selektor zusammengefasst werden, um dateigröße zu sparen und die wartbarkeit zu verbessern

2018-02-09 09:24 UTC, felixdausch approved these changes

2018-02-09 09:25 UTC, merged