Feature/translation service
plentymarkets/plugin-ceres pull request #269
Opened 2018-01-19 10:40 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested

@plentymarkets/ceres-io 

requires: https://github.com/plentymarkets/plugin-io/pull/111

2018-01-22 17:05 UTC, lks-mtzn requested changes

2018-01-22 17:05 UTC, lks-mtzn commented on resources/js/src/app/components/itemList/ItemSearch.js
> +            document.title = TranslationService.tranylate("Ceres::Template.generalSearchResults") + " " + searchString + " | " + App.config.shopName;
Typo?

2018-01-22 17:05 UTC, lks-mtzn commented on resources/js/src/app/services/TranslationService.js
> +const TranslationService = (function($)
Kannst du das nicht als normale Klasse schreiben?

2018-01-23 15:57 UTC, felixdausch commented on resources/js/src/app/components/itemList/ItemSearch.js
> +            document.title = TranslationService.tranylate("Ceres::Template.generalSearchResults") + " " + searchString + " | " + App.config.shopName;
👍

2018-01-23 15:58 UTC, felixdausch commented on resources/js/src/app/services/TranslationService.js
> +const TranslationService = (function($)
ES6-Klassen ermöglichen nicht das Kapseln von privaten Methoden oder Properties. Daher die Konstruktion als IIFE

2018-01-24 08:34 UTC, lks-mtzn approved these changes

2018-01-26 08:11 UTC, merged