using intersect instead of lazy-hydrate
plentymarkets/plugin-ceres pull request #2851
Opened 2021-05-12 09:55 UTC by MaxBentz

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io

using intersect instead of lazy-hydrate as fallback in case of not using the vue-ssr feature.

2021-05-12 11:12 UTC, MaxBentz commented
<template #loading> need to be defined

2021-05-17 13:08 UTC, felixgehrmann requested changes

2021-05-17 13:08 UTC, felixgehrmann commented on resources/views/PageDesign/Partials/Header/DefaultHeader.twig
> +                                                </intersect>
```suggestion
                                                    <template #loading>
                                                        <div class="row" style="height:1px;"></div>
                                                    </template>
                                                </intersect>
```

2021-05-17 13:08 UTC, felixgehrmann commented on resources/views/Widgets/Header/TopBarWidget.twig
> +                                        </intersect>
```suggestion
                                            <template #loading>
                                                <div class="row" style="height:1px;"></div>
                                            </template>
                                        </intersect>
```

2021-05-17 13:08 UTC, felixgehrmann commented
Hey @MaxBentz,
thanks for the PR! 
I've added our recommendation for loading templates as suggestions. 👍

2021-05-18 09:03 UTC, felixgehrmann approved these changes

2021-05-18 09:03 UTC, merged