Dcj/feature/js language detection
plentymarkets/plugin-ceres pull request #2907
Opened 2021-06-14 08:46 UTC by pfrincu-plenty

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io

2021-06-18 13:36 UTC, felixdausch submitted a review, later dismissed
Please move the different cases during initialization to different methods to keep the code more readable.
Do you really need two flags to be stored in the localStorage? If yes, please find more speaking names that describe better, whats the purpose of each of these flags.

Finally we need to take care of the GDPR. So the flags are only allowed to be stored if the user has accepted the usage. For this you need to hook in the cookie bar of Ceres as described here:
https://developers.plentymarkets.com/en-gb/developers/main/plentyshop-plugins/how-to-register-cookies.html

2021-06-18 13:36 UTC, felixdausch commented on resources/views/Widgets/Header/LanguageDetectionWidget.twig
> +        {% else %}
If possible, the preview should look like the production output of the widget. You should be able to use your Vue component in the preview as well. Maybe you need to check inside of your component if you are in the ShopBuilder to display the language picker even if the displayed language already matches the browser language. To do so, you can access `$ceres.isShopBuilder` inside of your Vue components.

2021-06-18 13:36 UTC, felixdausch commented on resources/scss/ceres/widgets/Header/_language-detection-widget.scss
> +  }
This isn't required. You can just add the class `bg-appearance` to apply the background color depending on the appearance-class

2021-06-18 13:36 UTC, felixdausch commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +    props: ["redirect", "appearance", "texttranslations", "buttontranslations"],
Please use the object syntax to define the props of this component to have at least a type check on the prop values:

https://vuejs.org/v2/api/#props

2021-06-18 13:36 UTC, felixdausch commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +      },
This shouldn't be necessary. You can access your props in the same way like you can access the components data. So `{{ appearance }}` will work even without this function

2021-06-18 13:36 UTC, felixdausch commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +        const textLangObj = JSON.parse(JSON.stringify(this.$props.texttranslations));
Why the json encoding/decoding here? The prop-value should already contain an accessible javascript object.

2021-06-18 13:36 UTC, felixdausch commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +        const buttonLangObj = JSON.parse(JSON.stringify(this.$props.buttontranslations));
Same as in `setText()`

2021-06-18 13:36 UTC, felixdausch commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +                window.location.href = linkTag.getAttribute('href')
Please use `navigateTo()` from UrlService.js

2021-06-18 13:36 UTC, felixdausch commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +              if (!window.localStorage.getItem('redirectActive')){
Why is this entry in the local storage required?

2021-06-18 14:21 UTC, cjohannsen requested changes

2021-06-18 14:21 UTC, cjohannsen commented on src/Widgets/Header/LanguageDetectionWidget.php
> +            ->withPosition(0)
this widget should not be the first one in the list (position 0)

2021-06-18 14:21 UTC, cjohannsen commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +        for (let i = 0; i < window.navigator.languages.length; i++) {
do not use for loops if not necessary, please use window.navigator.languages.forEach(language => ...)

2021-06-22 12:43 UTC, felixdausch commented on resources/scss/ceres/widgets/Header/_language-detection-widget.scss
> +  }
@Tim-M-S can this be removed regarding to your changes on the widget template?

2021-06-22 12:46 UTC, felixdausch commented on resources/js/src/app/components/pageDesign/LanguageDetection.vue
> +                window.location.href = linkTag.getAttribute('href')
See https://github.com/plentymarkets/plugin-ceres/blob/stable/resources/js/src/app/services/UrlService.js#L162

2021-06-25 15:18 UTC, Tim-M-S commented on resources/lang/de/Widget.properties
> +languageDetectionRedirect = "Automatische Weiterleitung aktivieren"
```suggestion
languageDetectionRedirect = "Automatische Weiterleitung aktivieren"

```

2021-06-28 09:47 UTC, Tim-M-S submitted a review, later dismissed

2021-06-28 09:47 UTC, cjohannsen submitted a review, later dismissed

2021-06-28 12:24 UTC, Tim-M-S approved these changes

2021-06-28 13:45 UTC, merged