Configurable bundle prefixes: use setting
plentymarkets/plugin-ceres pull request #3019
Opened 2021-09-08 12:46 UTC by raphael-adam

Wir haben Einstellung für die Präfixe bei Bundles geschaffen (früher fest `[BUNDLE]` und `[-]`). Das soll dann hier über die Einstellung geladen werden.

@plentymarkets/ceres-io bitte gut prüfen, ich hab noch nie was bei Ceres gemacht 🙂 . Der String `[BUNDLE]` wird auch noch in `itemBundleName.filter.js` verwendet. Muss die Stelle auch angepasst werden? In der Bestellübersicht und in MyAccount hatte mit der Anpassung in `ItemName.twig` gepasst soweit ich das sehen konnte.

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io
@plentymarkets/team-order-payment 

https://plentymarkets.kanbanize.com/ctrl_board/75/cards/202079/details/

2021-09-09 05:10 UTC, j-konopka approved these changes, later dismissed

2021-09-09 08:53 UTC, estafilarakis commented on resources/views/PageDesign/Macros/ItemName.twig
> +        {% set itemName = services.order.removeBundlePrefix(itemName) %}
Wie mein Vorschlag im IO-PR: hier wurde in der alten Logik das Ergebnis der Ersetzung noch durch `trim` gejagt, um das führende Leerzeichen zu entfernen.

2021-09-16 12:20 UTC, stentrop commented
Das JS sowie weitere Stellen in den Templates müssen angepasst werden.


 @raphael-adam 


https://github.com/plentymarkets/plugin-ceres/blob/stable/resources/views/Widgets/OrderConfirmation/PurchasedItemsWidget.twig#L24

https://github.com/plentymarkets/plugin-ceres/blob/stable/resources/views/Checkout/OrderDetails.twig#L149

https://github.com/plentymarkets/plugin-ceres/blob/stable/resources/views/MyAccount/Partials/OrderHistoryListItemDetails.twig#L21

2021-09-16 12:35 UTC, stentrop requested changes
Siehe Kommentar

2021-09-21 11:42 UTC, stentrop submitted a review, later dismissed

2021-09-21 11:46 UTC, estafilarakis submitted a review, later dismissed

2021-09-22 15:37 UTC, Tim-M-S approved these changes

2021-09-23 06:15 UTC, estafilarakis approved these changes

2021-10-04 10:41 UTC, merged