FEATURE: Show property with additional costs in single item and baske…
plentymarkets/plugin-ceres pull request #3113
Opened 2021-12-06 07:58 UTC by stentrop

…t view

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/plentyshop

2021-12-06 07:59 UTC, stentrop commented
<img width="1568" alt="Bildschirmfoto 2021-12-06 um 08 58 53" src="https://user-images.githubusercontent.com/13133283/144808883-72ea99ea-9131-4db4-9716-884faddc474c.png">

2022-02-16 14:16 UTC, lks-mtzn approved these changes

2022-02-16 14:16 UTC, lks-mtzn commented on resources/js/src/app/components/basket/list/BasketListItem.vue
> +          const property = this.basketItem.variation.data.properties.find(property => property.property.id === parseInt(propertyId));
Hier suchst du die selbe Property aus der du die ID ausließt.

2022-02-16 14:16 UTC, lks-mtzn commented on resources/js/src/app/components/item/ItemPrice.vue
> +       const property = this.currentVariation.properties.find(property => property.property.id === parseInt(propertyId));
Hier auch.

2022-02-16 14:18 UTC, lks-mtzn requested changes
.

2022-03-02 12:10 UTC, Tim-M-S submitted a review, later dismissed

2022-03-02 14:24 UTC, Tim-M-S submitted a review, later dismissed

2022-03-22 14:48 UTC, maxiroellplenty commented on resources/lang/de/Template.properties
> +basketAdditionalCosts = "Zusatzkosten (Preis pro Artikel)"
Add missing translations for en/fr/nl/pl

2022-03-23 16:46 UTC, maxiroellplenty approved these changes

2022-03-23 16:47 UTC, lks-mtzn approved these changes

2022-03-23 16:48 UTC, merged