ADD csrf token mismatch exepction listener and reload on exception
plentymarkets/plugin-ceres pull request #3193
Opened 2022-01-27 16:41 UTC by cjohannsen

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/plentyshop

2022-01-28 07:33 UTC, stentrop commented
Dann werden die anderen Fehler nicht mehr markiert oder ?  

Warum 9999 ?

2022-02-08 09:45 UTC, maxiroellplenty approved these changes

2022-02-08 09:55 UTC, maxiroellplenty requested changes

2022-02-08 09:55 UTC, maxiroellplenty commented on resources/lang/de/Template.properties
> +csrfTokenMismatch = "Der Token des CSRF-Cookies war nicht korrekt. Sie wurden zum Login weitergeleitet."
Text anpassen

2022-02-08 13:36 UTC, maxiroellplenty commented on resources/lang/de/Template.properties
> +csrfTokenMismatch = "Der Token des CSRF-Cookies war nicht korrekt. Sie wurden zum Login weitergeleitet."
```suggestion
csrfTokenMismatch = "Sie wurden aus Sicherheitsgründen abgemeldet. Sie werden zum Login weitergeleitet."
```

2022-02-08 13:51 UTC, maxiroellplenty approved these changes

2022-02-08 14:51 UTC, merged