FEATURE: Softlogin page
plentymarkets/plugin-ceres pull request #3212
Opened 2022-02-14 15:11 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/plentyshop

2022-02-16 14:29 UTC, maxiroellplenty approved these changes, later dismissed

2022-02-17 09:12 UTC, maxiroellplenty submitted a review, later dismissed

2022-02-21 09:40 UTC, felixdausch requested changes
- resources/views/Checkout/OrderConfirmationSoftlogin.twig würde ich zwecks Einheitlichkeit umbenennen zu "OrderConfirmationSoftLogin.twig"

2022-02-21 09:40 UTC, felixdausch commented on resources/views/Checkout/OrderConfirmationSoftlogin.twig
> +        {% set overrideConfirmationSoftlogin = LayoutContainer.show("Ceres::OrderConfirmationSoftLogin.Override") %}
Wollen wir noch ein Überschreiben per LayoutContainer anbieten oder reicht uns das Überschreiben per ShopBuilder?

2022-02-21 09:40 UTC, felixdausch commented on src/Contexts/OrderConfirmationContext.php
> +    public $orderInputType = 'name';
Können wir für die möglichen Werte noch Konstanten im Kern bereitstellen?

2022-02-21 09:40 UTC, felixdausch commented on src/Contexts/OrderConfirmationContext.php
> +            $orderConfirmationToken = $sessionStorage->getSessionValue('orderConfirmationToken') ?? '';
Warum müssen wir den Token durch den Context schleifen und können nicht kernseitig direkt aus der session lesen?

2022-02-21 09:40 UTC, felixdausch commented on src/Contexts/OrderConfirmationContext.php
> +            $this->orderAccessKey = $orderArray['order']['accessKey'];
Wir übergeben ja schon die OrderId an die softlogin-Twig-Funktion. Damit müssten wir auch kernseitig an den AccessKey kommen. Da Auftragsdaten im RAM gecached werden, sollte es auch keine doppelten Queries mit sich bringen

2022-03-15 16:06 UTC, maxiroellplenty approved these changes

2022-03-16 09:06 UTC, felixdausch approved these changes

2022-03-16 09:06 UTC, merged