Add toggleable classes
plentymarkets/plugin-ceres pull request #3232
Opened 2022-02-28 12:06 UTC by danielgaiduk

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/plentyshop

2022-03-01 18:08 UTC, cjohannsen requested changes

2022-03-01 18:08 UTC, cjohannsen commented on resources/views/Widgets/Category/ItemGridWidget.twig
> +<div class="widget widget-item-grid widget-{{ appearance }}{% if customClass | length > 0 %} {{ customClass }}{% endif %}{% if spacingMargin | length > 0 %} {{ spacingMargin }}{% endif %}" {% if inli
Momentan setzt du die Klassen als Attribut auf das Element. Ich glaube so sollte es aussehen (check du es auch noch mal):

```suggestion
<div class="widget widget-item-grid widget-{{ appearance }}{% if customClass | length > 0 %} {{ customClass }}{% endif %}{% if spacingMargin | length > 0 %} {{ spacingMargin }}{% endif %}{% if noVat %} item-vat-hidden{% endif %}{% if grayBackground %} item-bg-gray{% endif %}" {% if inlineMargin | length > 0 %} style="{{ inlineMargin }}"{% endif %}>
```

2022-03-01 18:08 UTC, cjohannsen commented on resources/views/Widgets/Common/ItemListWidget.twig
> +<div class="widget widget-item-list widget-{{ widget.settings.appearance.mobile | default('primary') }}{% if customClass | length > 0 %} {{ customClass }}{% endif %}{% if spacingMargin | length > 0 %
hier werden die Klassen auch als Attribut gesetzt

2022-03-01 18:08 UTC, cjohannsen commented on src/Widgets/Category/ItemGridWidget.php
> +        $settings->createCheckbox('noVat')
bitte doppelte Anführungszeichen verwenden

2022-03-01 18:08 UTC, cjohannsen commented on src/Widgets/Common/ItemListWidget.php
> +        $settings->createCheckbox('noVat')
bitte doppelte Anführungszeichen verwenden

2022-03-02 13:27 UTC, danielgaiduk commented on resources/views/Widgets/Common/ItemListWidget.twig
> +<div class="widget widget-item-list widget-{{ widget.settings.appearance.mobile | default('primary') }}{% if customClass | length > 0 %} {{ customClass }}{% endif %}{% if spacingMargin | length > 0 %
Done

2022-03-02 13:29 UTC, cjohannsen approved these changes

2022-03-02 13:30 UTC, merged