Add toggable btn-outline class
plentymarkets/plugin-ceres pull request #3243
Opened 2022-03-08 19:05 UTC by danielgaiduk

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/plentyshop

2022-03-11 17:13 UTC, cjohannsen requested changes

2022-03-11 17:13 UTC, cjohannsen commented on src/Widgets/Basket/CouponWidget.php
> +        $settingsFactory->createCheckbox('outline')
doppelte Anführungszeichen in jeder PHP Datei

2022-03-11 17:13 UTC, cjohannsen commented on resources/lang/de/Widget.properties
> +itemListOutlineLabel = "Umrandung"
Ich glaube sowas passt hier besser, aber am besten sollte Franz hier noch mal schauen

```suggestion
itemListOutlineLabel = "Umriss des Buttons einfärben"
```

2022-03-11 17:13 UTC, cjohannsen commented on resources/scss/ceres/widgets/Helper/_widget-appearance.scss
> +@use "sass:selector";
hier noch mal sichergehen dass das im build prozess läuft (auch devcloud)

2022-03-11 17:13 UTC, cjohannsen commented on resources/views/Widgets/Category/ToolbarWidget.twig
> +<div class="widget widget-toolbar list-controls{% if customClass | length > 0 %} {{ customClass }}{% endif %}{% if spacingMargin | length > 0 %} {{ spacingMargin }}{% endif %}{% if outline %} btn-out
Ich sehe hier überhaupt keine Auswirkung

2022-03-11 19:08 UTC, stentrop commented on src/Widgets/Basket/CouponWidget.php
> +        $settingsFactory->createCheckbox('outline')
Das ist schon so okay. Wo möglich mit einfachen arbeiten in php Dateien.

2022-03-14 20:29 UTC, danielgaiduk commented on resources/lang/de/Widget.properties
> +itemListOutlineLabel = "Umrandung"
Label ist gesetzt, ich schreibe ihm, sobald er da ist

2022-03-14 20:29 UTC, danielgaiduk commented on resources/scss/ceres/widgets/Helper/_widget-appearance.scss
> +@use "sass:selector";
Funktioniert

2022-03-14 20:29 UTC, danielgaiduk commented on resources/views/Widgets/Category/ToolbarWidget.twig
> +<div class="widget widget-toolbar list-controls{% if customClass | length > 0 %} {{ customClass }}{% endif %}{% if spacingMargin | length > 0 %} {{ spacingMargin }}{% endif %}{% if outline %} btn-out
Ist gefixt mit dem neusten Commit

2022-03-15 17:11 UTC, cjohannsen approved these changes

2022-03-15 17:12 UTC, merged