Feature/payment method already paid
plentymarkets/plugin-ceres pull request #3369
Opened 2022-12-14 15:26 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/plentyshop

2022-12-14 20:45 UTC, stentrop requested changes

2022-12-14 20:45 UTC, stentrop commented on src/Config/CeresCheckoutConfig.php
> +    public $alreadyPaidIconUrl;
if we can we should use types

2022-12-14 20:45 UTC, stentrop commented on src/Methods/AlreadyPaidPaymentMethod.php
> +    private $basketRepository;
types ?

2022-12-14 20:45 UTC, stentrop commented on src/Wizard/ShopWizard/Repositories/AlreadyPaidShippingCountryRepository.php
> +    public function saveShippingCountries(int $plentyId, array $shippingCountryIds)
return types

2022-12-14 20:45 UTC, stentrop commented on src/Wizard/ShopWizard/Services/AlreadyPaidShippingCountriesService.php
> +    public function execute(int $plentyId, array $shippingCountriesIds)
so we always delete all entries ?

2022-12-14 20:45 UTC, stentrop commented on src/Wizard/ShopWizard/Services/SettingsHandlerService.php
> +    public function getAlreadyPaidShippingCountries($plentyId)
type

2022-12-14 20:45 UTC, stentrop commented on src/Wizard/ShopWizard/Steps/Builder/OnlineStoreStep.php
> +            $systemLanguage = $this->getLanguage();
systemLanguage !==  LocaleLanguage

2022-12-16 15:05 UTC, Dominik2809 commented on src/Wizard/ShopWizard/Services/AlreadyPaidShippingCountriesService.php
> +    public function execute(int $plentyId, array $shippingCountriesIds)
yes

2022-12-19 12:50 UTC, Tim-M-S approved these changes

2022-12-19 13:26 UTC, merged