Franz/changelog and wizard already paid 5.0.57
plentymarkets/plugin-ceres pull request #3371
Opened 2022-12-20 09:58 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/plentyshop

2022-12-21 07:48 UTC, Dominik2809 requested changes

2022-12-21 07:48 UTC, Dominik2809 commented on resources/lang/en/Wizard.properties
> +deliveryCountryDescription = The assistant for delivery countrys helps you set up a country of delivery for the online store.
countries?

2022-12-21 07:59 UTC, Dominik2809 submitted a review, later dismissed

2023-01-03 12:01 UTC, felixgehrmann approved these changes

2023-01-03 12:02 UTC, merged