ADD translations
plentymarkets/plugin-ceres pull request #341
Opened 2018-03-07 09:14 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested

@plentymarkets/ceres-io

2018-03-07 13:21 UTC, felixdausch reviewed
@fmutschler Bitte die Texte nochmals prüfen

2018-03-13 09:51 UTC, lks-mtzn approved these changes

2018-05-09 09:46 UTC, lks-mtzn requested changes

2018-05-09 09:46 UTC, lks-mtzn commented on resources/lang/en/Template.properties
> +basketItemsRemovedForLanguage = "Items have been removed from the shopping cart because they are not available in the selected language."
Die Texte müssten noch mal an die neue Property Struktur angepasst werden.

2018-09-12 05:12 UTC, dbohla commented
@Dominik2809 Kann der PR nicht geschlossen werden?

2018-10-19 13:44 UTC, closed without merging