Added toggle and mapping for webp conversion setting
plentymarkets/plugin-ceres pull request #3447
Opened 2023-10-17 12:23 UTC by teodorrosusn

2023-10-24 12:07 UTC, Dominik2809 approved these changes

2023-10-24 12:09 UTC, Dominik2809 requested changes, later dismissed
changelog entries

2024-02-27 07:10 UTC, fmutschler submitted a review, later dismissed
Die plentymarkets Seite zu Preisen, die wir im Assistenten verlinken, gibt leider erstmal gar keine Auskunft zu den Content/Artikelbilder-Kosten :(
Sollen wir das trotzdem drin lassen?

2024-03-05 14:48 UTC, csandru-plenty submitted a review, later dismissed

2024-03-05 14:51 UTC, ksted submitted a review, later dismissed

2024-03-06 09:05 UTC, ksted approved these changes

2024-03-06 12:25 UTC, merged