Added feedback data to itemList rest call
plentymarkets/plugin-ceres pull request #3459
Opened 2023-11-29 15:38 UTC by luisaha

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Changes to SCSS have been accounted for in plentyShop LTS Modern

@plentymarkets/plentyshop

2023-11-29 20:55 UTC, stentrop approved these changes, later dismissed

2023-11-30 15:18 UTC, maxiroellplenty requested changes
Please add a changelog entry, also if they are available anyway could we refactor the current way we display/load the stars? @stentrop

2023-12-01 08:29 UTC, stentrop commented
@maxiroellplenty 
yes we can also update the feedback plugin logic tu use this fields and set a dependency to the newest LTS version

2024-01-10 13:08 UTC, stentrop approved these changes

2024-01-10 14:24 UTC, maxiroellplenty approved these changes

2024-01-10 14:25 UTC, merged