Feat/manufacturer data widget
plentymarkets/plugin-ceres pull request #3623
Opened 2024-12-05 07:26 UTC by ivladu-plenty

AB#139031
### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Changes to SCSS have been accounted for in plentyShop LTS Modern

@plentymarkets/plentyshop

2024-12-11 12:44 UTC, fmutschler requested changes

2024-12-11 12:44 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +itemManufacturerLabel = "Item manufacturer"
Here, you added the German entries to the English properties file (and vice versa).

```suggestion
itemManufacturerLabel = "Item manufacturer"
itemManufacturerSampleName = "Name 1"
itemManufacturerSampleCompanyName = "Acme Company"
itemManufacturerSampleAddress = "Main Street 12"
itemManufacturerSampleLocation = "56009 Anytown Germany"
itemManufacturerSampleDomain = "info@sampledomain.com"
itemManufacturerSampleHomepage = "www.samplehomepage.com"
itemManufacturerSamplePhone = "+123456789"
```

2024-12-11 12:44 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +itemManufacturerLabel = "Item manufacturer"
Here, you added the English translations to the DE properties file (and vice versa)

```suggestion
itemManufacturerLabel = "Artikelhersteller"
itemManufacturerSampleName = "Name 1"
itemManufacturerSampleCompanyName = "Musterhersteller"
itemManufacturerSampleAddress = "Musterstraße 12"
itemManufacturerSampleLocation = "12209 Musterstadt Deutschland"
itemManufacturerSampleDomain = "info@musterdomain.com"
itemManufacturerSampleHomepage = "www.musterhomepage.com"
itemManufacturerSamplePhone = "+123456789"
```

2024-12-12 13:52 UTC, abocsan-plenty approved these changes

2024-12-12 13:56 UTC, merged