Use generic urls to append trailing slashes if configured
plentymarkets/plugin-ceres pull request #398
Opened 2018-04-03 13:52 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io 

**requires:** https://github.com/plentymarkets/plugin-io/pull/182

2018-04-12 13:36 UTC, Sebsta13 submitted a review, later dismissed

2018-04-12 13:36 UTC, Strean1337 commented on resources/views/Category/Macros/CategoryTree.twig
> +    {% endif %}
kann man das nicht über die macros legen, dann spart man sich die selbe Logik 3 mal?

2018-04-20 07:48 UTC, felixdausch commented on resources/views/Category/Macros/CategoryTree.twig
> +    {% endif %}
Nein. Es ist nicht möglich, außerhalb von macros variablen zu definieren

2018-04-20 08:40 UTC, lks-mtzn requested changes

2018-04-20 08:40 UTC, lks-mtzn commented on resources/js/src/app/services/CategoryService.js
> -    window.history.replaceState({}, title, currentCategory.url + window.location.search);
Willst du hier noch die Änderungen von meinem anderem [Pullrequest](https://github.com/plentymarkets/plugin-ceres/pull/426) einbauen?

2018-05-07 11:42 UTC, lks-mtzn approved these changes

2018-05-07 11:44 UTC, merged