filter script and style tags for unique items. there could be duplica…
plentymarkets/plugin-ceres pull request #413
Opened 2018-04-12 12:18 UTC by marcusschmidt

…tes, if multipla dataproviders of one single plugin are used

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2018-04-12 13:38 UTC, Sebsta13 requested changes

2018-04-12 13:38 UTC, Strean1337 commented on meta/documents/changelog_de.md
> +- Durch einen Fehler wurden unter gewissen umständen script- und style-Tags mehrfach in ein Dokument eingefügt. Dies wurde behoben.
Den Changelog bitte entfernen, die Version hier stimmt nicht und es würde nur zu Missverständnissen kommen. Den Changelog einfrach @fmutschler schicken

2018-04-12 13:38 UTC, Strean1337 commented on meta/documents/changelog_en.md
> +- Under certain circumstances some script and style tags could be inserted more then once. This has been fixed.
same

2018-04-12 13:44 UTC, marcusschmidt commented
@fmutschler hast du mitgelesen?

2018-04-13 07:55 UTC, Sebsta13 approved these changes

2018-04-13 07:58 UTC, merged