change position from sale and promotional coupons
plentymarkets/plugin-ceres pull request #474
Opened 2018-05-24 17:58 UTC by stentrop

fix coupon logic and placeorder

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-06-01 10:50 UTC, felixdausch requested changes

2018-06-01 10:50 UTC, felixdausch commented on resources/lang/en/Template.properties
> +basketOpenAmount= "Zu zahlender Betrag"
Übersetzungen bitte mit @fmutschler abstimmen

2018-06-01 11:29 UTC, fmutschler submitted a review, later dismissed

2018-06-01 11:29 UTC, fmutschler commented on resources/lang/de/Template.properties
>  checkoutMethodOfPaymentChanged="Die von Ihnen ausgewähle Zahlart ist nicht mehr verfügbar."
"Die von Ihnen ausgewähle Zahlungsart ist nicht mehr verfügbar."

2018-06-01 11:29 UTC, fmutschler commented on resources/lang/en/Template.properties
> +basketOpenAmount= "Zu zahlender Betrag"
"Outstanding amount"

2018-06-01 11:29 UTC, fmutschler commented on resources/lang/en/Template.properties
> +checkoutOpenAmount = "Zu zahlender Betrag"
"Outstanding amount"

2018-06-04 11:05 UTC, felixdausch submitted a review, later dismissed

2018-06-05 09:34 UTC, Sebsta13 approved these changes

2018-06-05 11:18 UTC, merged