Added logic to load favicon from config
plentymarkets/plugin-ceres pull request #480
Opened 2018-06-01 13:47 UTC by Strean1337

### All changes meet the following requirements
- [] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2018-06-01 13:48 UTC, Strean1337 commented
@fmutschler der neue Eintrag in der Config muss noch in die Doku aufgenommen werden.

2018-06-04 11:10 UTC, felixdausch requested changes

2018-06-04 11:10 UTC, felixdausch commented on resources/lang/de/Config.properties
> +globalCompanyIconLabel = Favicon des Webshops
warum nennst du den Key nicht auch `Favicon` sonder `CompanyIcon`? Wäre verständlicher...

2018-06-04 11:10 UTC, felixdausch commented on src/Config/CeresHeaderConfig.php
> +        $this->companyIcon          = $this->getTextValue( "header.company_icon", "" );
Benennung (s.o.)

2018-06-04 11:41 UTC, Strean1337 commented on resources/lang/de/Config.properties
> +globalCompanyIconLabel = Favicon des Webshops
hatte mich an den anderen orientiert. CompanyName und Logo

2018-06-08 15:28 UTC, felixdausch approved these changes

2018-06-11 08:50 UTC, merged