add individual error message for blocked logins
plentymarkets/plugin-ceres pull request #488
Opened 2018-06-08 10:58 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-06-08 14:11 UTC, Sebsta13 requested changes

2018-06-08 14:11 UTC, Strean1337 commented on resources/js/src/app/components/customer/login/Login.js
> +                        if (response.error.message.length > 0)
Sobald ein code kommt ist das Kundenkonto immer gesperrt?

2018-06-11 07:05 UTC, stentrop commented on resources/js/src/app/components/customer/login/Login.js
> +                        if (response.error.message.length > 0)
Sobald eine Message dran hängt, ist es gesperrt.

2018-06-11 10:52 UTC, Sebsta13 approved these changes

2018-06-11 10:53 UTC, merged