FIX item out of stock notification
plentymarkets/plugin-ceres pull request #556
Opened 2018-07-31 14:36 UTC by lks-mtzn

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-07-31 14:37 UTC, lks-mtzn commented
https://github.com/plentymarkets/plugin-io/pull/263

2018-08-01 09:56 UTC, Sebsta13 requested changes

2018-08-01 09:56 UTC, Strean1337 commented on resources/lang/de/Template.properties
> +notificationRemoveCouponMinimumOrderValueIsNotReached = "Der eingelöste Gutschein wurde entfernt. Der Mindestbestellwert wird nicht erreicht."
Der eingelöste Gutschein wurde entfernt. Der Mindestbestellwert wird nicht erreicht. <= Finde den part "wird nicht erreicht" i.wie irreführend.

Könnte man sowas schreiben wie:

Der eingelöste Gutschein wurde entfernt. Der Mindestbestellwert wird nicht **mehr** erreicht.

2018-08-01 09:56 UTC, Strean1337 commented on resources/lang/de/Template.properties
> +notificationRemoveCouponMinimumOrderValueIsNotReached = "Der eingelöste Gutschein wurde entfernt. Der Mindestbestellwert wird nicht erreicht."
@fmutschler

2018-08-01 11:09 UTC, fmutschler submitted a review, later dismissed

2018-08-01 11:09 UTC, fmutschler commented on resources/lang/de/Template.properties
> +notificationRemoveCouponMinimumOrderValueIsNotReached = "Der eingelöste Gutschein wurde entfernt. Der Mindestbestellwert wird nicht erreicht."
Guter Vorschlag!

2018-08-01 11:43 UTC, Sebsta13 submitted a review, later dismissed

2018-08-02 11:11 UTC, merged