Update picture alt title tags
plentymarkets/plugin-ceres pull request #560
Opened 2018-08-02 14:01 UTC by josthanken

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-08-03 08:48 UTC, josthanken commented
ItemLazyImg und CategoryListItemPreview sind von den Anpassungen ausgenommen, bitte einmal prüfen

2018-08-16 08:55 UTC, stentrop requested changes
Inkonsequentes Verhalten, 

mal wird der Artikelname genommen, mal der Alternativtext am Bild.

Der Title ist immer gleich des Alternativtexts, sollte auch nicht so sein.

Folgendes Verhalten gewünscht:

alt:    Alternativtext vom Bild, wenn leer dann Itemname
title:  Name vom Bild, wenn leer dann Itemname

2018-08-23 10:51 UTC, cjohannsen requested changes

2018-08-23 10:51 UTC, cjohannsen commented on resources/js/src/app/components/basket/list/BasketListItem.js
> +            return this.$options.filters.itemName(this.basketItem.variation.data);
return this.itemName instead

2018-08-24 12:38 UTC, cjohannsen approved these changes

2018-08-24 12:40 UTC, stentrop approved these changes

2018-08-24 12:46 UTC, merged