Feature/default sorting
plentymarkets/plugin-ceres pull request #58
Opened 2017-05-31 12:58 UTC by chkolb

2017-06-20 09:27 UTC, lks-mtzn requested changes

2017-06-20 09:27 UTC, lks-mtzn commented on meta/documents/changelog_de.md
> +- Die Artikelsortierung **Empfohlen** in der Kategorieansicht wurde hinzugefügt. Bis zu drei Werte können für eine komplexe Artikelsortierung verkettet werden. Diese Sortierung kann in Ceres über den
Den changelog musst noch mal anpassen und das in 1.2.7 schieben

2017-06-20 09:27 UTC, lks-mtzn commented on config.json
> +            "item.notSelected"                          : "Not selected",
Änder das noch mal auf einen anderen Key.

2017-06-20 09:27 UTC, lks-mtzn commented on config.json
> +            "item.notSelected"                          : "Not selected",
Hier auch

2017-06-20 09:27 UTC, lks-mtzn commented on config.json
> +            "item.notSelected"                          : "Not selected",
+

2017-06-20 09:27 UTC, lks-mtzn commented on config.json
> +            "item.notSelected"                          : "Not selected",
+

2017-06-20 09:29 UTC, lks-mtzn commented on config.json
> +            "variation.availability.averageDays_asc"    : "Variation availability (ascending)",
Änder das noch mal überall auf 'Availability ...'

2017-06-20 13:40 UTC, lks-mtzn requested changes

2017-06-20 13:40 UTC, lks-mtzn commented on config.json
> +        "default"       : "item.manufacturer.name_asc"
Hier ist noch der falsche key da muss externalName hin.

2017-06-26 15:52 UTC, Sebsta13 approved these changes

2017-06-26 15:52 UTC, Sebsta13 commented on config.json
> +            "default.standard_sorting"          : "Recommended",
nenn es am besten default.recommended_sorting oder so. Nur eine Kleinigkeit aber das naming passt nicht so.

2017-06-26 15:52 UTC, Sebsta13 commented on config.json
> +        "default"                   : "default.standard_sorting, texts.name1_asc, texts.name1_desc, itemPrice_asc"
hier dann dementsprechend anpassen

2017-06-26 15:52 UTC, Sebsta13 commented on config.json
> +            "default.standard_sorting"          : "Recommended",
same

2017-06-26 15:52 UTC, Sebsta13 commented on resources/js/src/app/components/itemList/ItemListSorting.js
> +                "default.standard_sorting"   : "itemStandardSorting",
hier dann auch ^^

2017-07-04 11:30 UTC, lks-mtzn approved these changes

2017-07-04 11:30 UTC, merged