Feature/contact form specific errors
plentymarkets/plugin-ceres pull request #602
Opened 2018-09-05 12:48 UTC by mdierkes

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-09-05 13:36 UTC, stentrop approved these changes

2018-09-10 08:07 UTC, lks-mtzn requested changes

2018-09-10 08:07 UTC, lks-mtzn commented on resources/js/src/app/components/customer/ContactForm.js
> +                            TranslationService.translate("Ceres::Template." + this._mapInvalidField(invalidField.dataset.model))
Ich würde vllt nicht für jedes invalidField einen eigenen Error ausgeben. In meinem PR gibt es quasi die selbe Stelle vllt kannst du dort noch mal schauen.

2018-09-10 11:06 UTC, lks-mtzn approved these changes

2018-09-11 08:36 UTC, merged