Feature/reduce data
plentymarkets/plugin-ceres pull request #635
Opened 2018-10-04 07:40 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-10-04 11:50 UTC, stentrop approved these changes

2018-10-05 06:17 UTC, stentrop commented on resources/views/ResultFields/CategoryTree.fields.json
> +    "details.nameUrl"
brauchen wir hier nicht nur noch den metaTitle und die canonical ?

2018-10-05 06:17 UTC, stentrop requested changes
Siehe resultField

2018-10-05 07:51 UTC, JVolke commented on resources/views/ResultFields/CategoryTree.fields.json
> +    "details.nameUrl"
Canonical und metaTitle kommen aus einem anderen "Topf" daher braucht man die an dieser Stelle nicht.

2018-10-05 13:26 UTC, felixdausch commented on resources/views/ResultFields/CategoryTree.fields.json
> +    "details.nameUrl"
metaTitle wird tatsächlich benötigt. Im CategoryService wird beim Wechsel der Kategorie der metaTitle ersetzt. Die Canonical wird derzeit in der Navigation nicht verwendet.

Beide Punkte sollten wir separat nochmal diskutieren.

2018-10-08 07:36 UTC, stentrop approved these changes

2018-10-08 08:14 UTC, merged