ADD event propagation plugin for vuex
plentymarkets/plugin-ceres pull request #659
Opened 2018-10-17 11:31 UTC by lks-mtzn

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-10-17 13:33 UTC, felixdausch requested changes

2018-10-17 13:33 UTC, felixdausch commented on resources/js/src/app/store/index.js
> +        if (App.config.log.performanceLevel === "development")
Hier würde ich NotificationService.log verwenden. Diese ist abhängig vom konfigurierten Log-Level und nicht vom Performance-Level

2018-10-17 13:33 UTC, felixdausch commented on resources/js/src/app/store/index.js
> +        const eventName = "on" + mutation.type[0].toUpperCase() + mutation.type.slice(1);
Du verwendest hier den Array-Zugriff auf einen String. Das funktioniert warscheinlich, sauberer wären jedoch Methoden aus der String-Klasse:
```
"on" + mutation.type.charAt(0).toUpperCase() + mutation.type.substr(1);
```

2018-10-18 11:26 UTC, Sebsta13 approved these changes

2018-10-18 11:31 UTC, merged