FIX remove basket items without lang in the selected language
plentymarkets/plugin-ceres pull request #670
Opened 2018-10-19 13:51 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-11-05 16:04 UTC, cjohannsen requested changes

2018-11-05 16:04 UTC, cjohannsen commented on resources/js/src/app/store/modules/BasketModule.js
> +                        $(document.body).trigger("sticky_kit:recalc");
This trigger needs to be executed after the basket items are loaded. Put it into the inner ApiService response.

2018-11-05 16:07 UTC, fmutschler requested changes

2018-11-05 16:07 UTC, fmutschler commented on resources/lang/en/Template.properties
> +notificationsBasketItemsRemoved = "Items have been removed from your shopping cart because they are actual not available."
"Items have been removed from your shopping cart because they are currently not available."

2018-11-06 13:06 UTC, cjohannsen approved these changes

2018-11-06 13:08 UTC, fmutschler approved these changes

2018-11-06 13:09 UTC, merged