remove unnecessary :hyphen in english language files
plentymarkets/plugin-ceres pull request #686
Opened 2018-10-25 02:39 UTC by mkreusch

:hyphen (to be replaced with &shy;) does not make any sense at the end of a word because it is only necessary for marking break points in long words.
This is probably an artefact of copying the German file.

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ x ] Changes have been tested
- [ x ] Plugin can be built

@plentymarkets/ceres-io

2018-10-25 08:30 UTC, fmutschler requested changes

2018-10-25 08:30 UTC, fmutschler commented on resources/lang/en/Template.properties
> +contactAcceptFormPrivacyPolicy = "Please accept the Privacy policy."
"Please accept the privacy policy."
-> privacy should be lower-case, not "Privacy"

2018-10-25 09:52 UTC, mkreusch commented
@fmutschler 
I updated the PR

2018-11-01 14:46 UTC, fmutschler approved these changes

2018-11-14 08:28 UTC, merged