Feature/redesign checkout
plentymarkets/plugin-ceres pull request #707
Opened 2018-11-09 13:52 UTC by Tim-M-S

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-11-10 14:30 UTC, felixdausch requested changes

2018-11-10 14:30 UTC, felixdausch commented on resources/css/ceres.css
> +    padding: 0 15px;
Hier würde ich auf eine sinnvolle SCSS-Variable zurückgreifen. (z.B. `$grid-gutter-width / 2`, um den Abstand an das Basis-Grid anzupassen)

2018-11-12 12:17 UTC, Tim-M-S commented on resources/css/ceres.css
> +    padding: 0 15px;
done

2018-11-14 08:28 UTC, felixdausch approved these changes

2018-11-16 16:06 UTC, merged