Feature/automatic email
plentymarkets/plugin-ceres pull request #708
Opened 2018-11-09 17:16 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-11-10 14:26 UTC, felixdausch requested changes

2018-11-10 14:26 UTC, felixdausch commented on resources/lang/en/Template.properties
> +resetPwMailSubject = "Resetting your password" ; deprecated
Ist es möglich / sinnvoll, die Übersetzungen in das E-Mail-Template zu migrieren? Andernfalls muss ein TODO in den Changelog!

2018-11-12 07:57 UTC, stentrop commented on resources/lang/en/Template.properties
> +resetPwMailSubject = "Resetting your password" ; deprecated
nein, ist nicht möglich. 

Das TODO haben wir aber im Sprint.

2018-11-14 08:30 UTC, felixdausch approved these changes

2018-11-22 08:50 UTC, merged