Feature/change payment
plentymarkets/plugin-ceres pull request #73
Opened 2017-06-20 09:01 UTC by Strean1337

@lks-mtzn 
@zhajjhassan

2017-06-20 10:04 UTC, lks-mtzn requested changes

2017-06-20 10:04 UTC, lks-mtzn commented on resources/js/src/app/components/myAccount/ChangePaymentMethod.js
> +        this.encodedPaymentMethods = JSON.parse(this.allowedPaymentMethods);
Check if needed.

2017-06-20 10:08 UTC, lks-mtzn commented on resources/js/src/app/components/myAccount/ChangePaymentMethod.js
> +                    this.closeModal();
Will man es nicht eher offen lassen? Oder macht das hier keinen Sinn?

2017-06-20 10:08 UTC, lks-mtzn commented on resources/lang/en/Template.properties
> +myAccountChangePaymentNotAllowed = "The payment method cannot be changed"
can't

2017-06-20 14:46 UTC, Strean1337 commented on resources/lang/en/Template.properties
> +myAccountChangePaymentNotAllowed = "The payment method cannot be changed"
not sure

2017-06-20 14:57 UTC, lks-mtzn commented on resources/js/src/app/components/myAccount/ChangePaymentMethod.js
> +            for (const paymentState in paymentStates)
Change to find.

2017-06-22 09:25 UTC, dbohla commented on resources/lang/en/Template.properties
> +myAccountChangePaymentNotAllowed = "The payment method cannot be changed"
cannot ist okay

2017-06-27 10:41 UTC, lks-mtzn approved these changes

2017-06-27 10:43 UTC, merged