Feature/search manufacturer by
plentymarkets/plugin-ceres pull request #730
Opened 2018-11-22 13:59 UTC by maxiroellplenty

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-12-13 16:18 UTC, cjohannsen requested changes

2018-12-13 16:18 UTC, cjohannsen commented on resources/views/Widgets/Common/ItemListWidget.json
> +            "required": true,
"required": false

2019-01-24 16:59 UTC, felixdausch commented on resources/lang/en/Widget.properties
> +itemListManufacturerTooltip = "Select Manufacturer"
@fmutschler

2019-01-28 13:18 UTC, cjohannsen requested changes

2019-01-28 13:18 UTC, cjohannsen commented on resources/views/Widgets/Common/ItemListWidget.json
> +                        "caption": "Widget.itemListManufacturer",
key -> itemListListTypeManufacturer

2019-01-30 15:50 UTC, cjohannsen approved these changes

2019-01-30 16:00 UTC, merged