Feature/live shopping rework
plentymarkets/plugin-ceres pull request #733
Opened 2018-11-26 15:51 UTC by cjohannsen

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-11-26 16:00 UTC, felixdausch requested changes

2018-11-26 16:00 UTC, felixdausch commented on resources/lang/de/Template.properties
> +liveShoppingBefore = "Statt:"
Kannst du den Preis nicht als Variable übergeben? Dadurch hat der Anwender mehr Formatierungsmöglichkeiten.

2018-11-27 09:04 UTC, cjohannsen commented on resources/lang/de/Template.properties
> +liveShoppingBefore = "Statt:"
done

2018-11-27 10:21 UTC, felixdausch approved these changes

2018-11-27 10:21 UTC, merged

2018-11-27 10:22 UTC, felixdausch commented on resources/lang/en/Template.properties
> +liveShoppingBefore = "Before: <del>:price</del>"
Kann das `<del>` nicht teil der Variable sein? Dann müssten wir die Übersetzung nicht mit `| raw`-Filter ausgeben