Feature/update sorting options
plentymarkets/plugin-ceres pull request #74
Opened 2017-06-20 09:52 UTC by lks-mtzn

2017-06-20 12:22 UTC, Sebsta13 requested changes

2017-06-20 12:22 UTC, Sebsta13 commented on config.json
> +            "variation.updatedAt_asc"                   : "Last variation update",
kann man das hier nicht auf mit den pfeilen darstellen?

2017-06-20 12:22 UTC, Sebsta13 commented on config.json
> +            "variation.updatedAt_asc"                   : "Last variation update",
this

2017-06-20 12:22 UTC, Sebsta13 commented on resources/lang/en/Template.properties
>  variationName_asc = "Variation name (ascending)"
variation name kann glaube einfach entfernt werden oder? Brauchen wir für nichts mehr.

2017-06-21 09:18 UTC, dbohla commented on resources/lang/en/Template.properties
>  variationName_asc = "Variation name (ascending)"
Wir müssten die .properties einmal komplett prüfen, weil die Sorting options da teilweise doppelt drin sind.

2017-06-21 09:27 UTC, Sebsta13 approved these changes

2017-06-21 09:29 UTC, merged