Feature/bootstrap 4 1 3
plentymarkets/plugin-ceres pull request #781
Opened 2019-01-07 15:14 UTC by felixdausch

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-01-07 15:40 UTC, lks-mtzn requested changes

2019-01-07 15:40 UTC, lks-mtzn commented on resources/js/src/app/components/customer/login/ForgotPassword.js
> +                .validate($("#reset-pwd-form-" + this._uid))
Sollte das vllt. auch auf `$refs`umgebaut werden wenn es weiter oben schon mal gemacht wurde?

2019-01-07 15:40 UTC, lks-mtzn commented on resources/js/src/app/directives/pageDesign/tooltip.js
> +const checkTooltip = (el, disable) =>
Finde das naming hier nicht so toll.

2019-01-07 15:40 UTC, lks-mtzn commented on resources/js/src/app/main.js
> +            /*
Kann das hier weg?

2019-01-08 09:38 UTC, lks-mtzn approved these changes

2019-01-08 10:13 UTC, cjohannsen approved these changes

2019-01-08 10:13 UTC, cjohannsen commented on config.json
> +                        "defaultValue": "#dc3545"
Nicht länger plenty rot?

2019-01-08 10:13 UTC, cjohannsen commented on resources/js/src/app/directives/pageDesign/tooltip.js
> +        if (window.matchMedia("(min-width: 768px)").matches)
Macht es hier vielleicht auch Sinn den breakpoint, wie bei stickInParent, per parameter zu setzen?

2019-01-08 10:32 UTC, merged