- Fix: paymentList after payment changed
plentymarkets/plugin-ceres pull request #81
Opened 2017-06-26 16:15 UTC by AHasenkampf

@lks-mtzn @Strean1337

2017-06-27 08:42 UTC, lks-mtzn requested changes

2017-06-27 08:42 UTC, lks-mtzn commented on resources/js/src/app/components/myAccount/ChangePaymentMethod.js
> +            for (const paymentId in paymentIds)
Mach das hier vllt. so:

paymentIds.find(entry => entry.typeId === 3)

2017-06-27 10:25 UTC, Strean1337 commented on resources/js/src/app/components/myAccount/ChangePaymentMethod.js
> +            for (const paymentId in paymentIds)
paymentIds.find(paymentId => paymentId.typeId === 3)

naming unso

2017-06-27 10:28 UTC, Strean1337 commented
gut das du es gefixt hast, wollte es auch eben fixen 👍

2017-06-27 11:17 UTC, Sebsta13 requested changes

2017-06-27 11:17 UTC, Strean1337 commented on resources/js/src/app/components/myAccount/ChangePaymentMethod.js
> +            if(paymentId != "undefined")
mein Fehler... if(paymentId) reicht.

@lks-mtzn

2017-06-27 13:28 UTC, lks-mtzn approved these changes

2017-06-28 15:02 UTC, Sebsta13 approved these changes

2017-06-28 15:14 UTC, merged