BasketListItem - display variation properties
plentymarkets/plugin-ceres pull request #842
Opened 2019-02-01 17:06 UTC by cjohannsen

Requires: https://github.com/plentymarkets/plugin-io/pull/371

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-02-04 10:42 UTC, lks-mtzn requested changes

2019-02-04 10:42 UTC, lks-mtzn commented on resources/js/src/app/helper/utils.js
> +export function orderArrayByKey(array, key, desc)
Du kannst hier stattdessen orderBy von lodash nehmen.

2019-02-04 10:42 UTC, lks-mtzn commented on resources/js/src/app/filters/variationProperties.filter.js
> +    if (propertyTypes.length)
Mach eine Schleife raus. Und Filter dann.

2019-02-04 10:42 UTC, lks-mtzn commented on resources/js/src/app/filters/variationProperties.filter.js
> +    for (const group of variationPropertyGroups)
Hier das selbe eig.

2019-02-19 13:19 UTC, cjohannsen commented
restart review

2019-02-20 12:08 UTC, felixdausch approved these changes

2019-02-20 12:31 UTC, lks-mtzn approved these changes

2019-02-20 12:36 UTC, merged