Feature/ added option to change aspect ratio of imageBox Widget
plentymarkets/plugin-ceres pull request #991
Opened 2019-03-19 14:20 UTC by Tim-M-S

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-03-19 14:42 UTC, fmutschler requested changes

2019-03-19 14:42 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +imageBoxAspectRatioThreeToTwo = "1,5 : 1"
```suggestion
imageBoxAspectRatioThreeToTwo = "3 : 2"
```

2019-03-19 14:42 UTC, fmutschler commented on resources/lang/de/Widget.properties
> +imageBoxAspectRatioTwoToThree = "1 : 1,5"
```suggestion
imageBoxAspectRatioTwoToThree = "2 : 3"
```

2019-03-19 14:42 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +imageBoxAspectRatioThreeToTwo = "1,5 : 1"
```suggestion
imageBoxAspectRatioThreeToTwo = "3 : 2"
```

2019-03-19 14:42 UTC, fmutschler commented on resources/lang/en/Widget.properties
> +imageBoxAspectRatioTwoToThree = "1 : 1,5"
```suggestion
imageBoxAspectRatioTwoToThree = "2 : 3"
```

2019-03-19 15:14 UTC, Tim-M-S commented on resources/lang/de/Widget.properties
> +imageBoxAspectRatioTwoToThree = "1 : 1,5"
done

2019-03-19 15:15 UTC, Tim-M-S commented on resources/lang/en/Widget.properties
> +imageBoxAspectRatioTwoToThree = "1 : 1,5"
done

2019-03-19 15:15 UTC, Tim-M-S commented on resources/lang/en/Widget.properties
> +imageBoxAspectRatioThreeToTwo = "1,5 : 1"
done

2019-03-19 15:15 UTC, Tim-M-S commented on resources/lang/de/Widget.properties
> +imageBoxAspectRatioThreeToTwo = "1,5 : 1"
done

2019-03-19 15:15 UTC, fmutschler approved these changes

2019-03-21 12:03 UTC, felixdausch requested changes

2019-03-21 12:03 UTC, felixdausch commented on resources/views/Widgets/Common/ImageBoxWidget.json
> +                        "value": "prop-xs-3-1",
ich würde die Werte jeweils nur "3-1", "2-1", "1-1", etc nennen und dann im Widget-Template `prop-xs-{{ aspectRatio }}` ausgeben. Auf diese Weise können die Einstellungen später einfacher für verschiedene Breakpoints aufgebohrt werden, falls diese Anforderung auf uns zu kommt.

2019-03-21 15:18 UTC, Tim-M-S commented on resources/views/Widgets/Common/ImageBoxWidget.json
> +                        "value": "prop-xs-3-1",
done

2019-03-21 16:31 UTC, felixdausch approved these changes

2019-03-21 16:55 UTC, merged